core/src/main/java/org/bitcoinj/core/TransactionBroadcast.java
The modified line here seems to have been assuming that `pinnedTx` was being initialized elsewhere, but it wasn't.  I'm not sure this is the correct fix.  If not, hopefully someone who understands this better can tell me what I'm missing.  Thanks.
=> NPE when invoking `PeerGroup.broadcastTransaction()` on peer group with no block chain.

core/src/main/java/org/bitcoinj/core/TransactionInput.java
This will make sure the fee is also known after a blockchain replay.
I noticed that with this change we could have done without persisting input values to the wallet protobuf, at least for transaction we created outselves.
=> When connecting outputs to inputs, cache its value in the input.

core/src/main/java/org/bitcoinj/core/PeerGroup.java
When PeerGroup stopped being a guava service in 27bc229, the javadocs were not updated. This PR updates them. 
Note: even if I don't understand why PeerGroup.stop() should be called, I left the suggestion there.
=> Updates PeerGroup's javadoc: PeerGroup is not a guava service 

core/pom.xml
The [default order](http://maven.apache.org/surefire/maven-surefire-plugin/test-mojo.html#runOrder) in maven-surefire-plugin is 'filesystem' which may produce different results across platforms
=> Run core tests in alphabetical order

core/src/main/java/org/bitcoinj/core/PeerSocketHandler.java
There is a bug when there is a incomplete message header at the end of the buffer 
This is the description of the bug:
Let's say PeerSocketHandler.receiveBuffer() is called with a Buffer of 65536 bytes which contains:
a) the last part of a Block message (65530 bytes) 
b) the first 6 bytes of the next Block message.
Part "a" is processed using a `largeReadBuffer`.
While processing part "b" https://github.com/bitcoinj/bitcoinj/blob/0a6f901b23524af1ee178174a35d06de3d0e29fd/core/src/main/java/org/bitcoinj/core/PeerSocketHandler.java#L149 throws `BufferUnderflowException` because it can not deserialize the whole message.
Since `i==0`, it attempts to use `largeReadBuffer`
Then https://github.com/bitcoinj/bitcoinj/blob/0a6f901b23524af1ee178174a35d06de3d0e29fd/core/src/main/java/org/bitcoinj/core/ …
=> bugfix for incomplete message headers at the end of the buffer

.gitignore
If we ignore them, it's easy to accidently remove them.
=> Don't gitignore wallet files.

core/src/main/java/org/bitcoinj/utils/BtcAutoFormat.java
Hi
I found this code with no effect while using FindBugs:
- setScale is called on immutable BigDecimal
- the returned new BigDecimal is not assigned
I'm not yet sure if there's more to it.
=> remove some calls to BigDecimal#setScale where returned objects are not used

core/src/main/java/org/bitcoinj/core/Transaction.java
Looks like the docblock for clearOutputs was copypasta from clearInputs
=> fix docblock for clearOutputs()

core/src/main/java/org/bitcoinj/core/Coin.java
This commit inlines the pseudo constant to the only method using it.
Due to cyclic dependencies (NetworkParameters vs. Coin) MAX_SATOSHIS
cannot be made a true constant.
=> Cleanup MAX_SATOSHIS pseudo-constant

core/src/main/java/org/bitcoinj/core/Address.java, core/src/test/java/org/bitcoinj/core/AddressTest.java
The issue became uncovered because the newly-for-0.13 introduced HttpDiscovery.Details member into MainNetParams broke the serialization chain for all mainnet addresses.
=> Address: Fix Java serialization and add serialization test case.

core/src/main/java/org/bitcoinj/store/MySQLFullPrunedBlockStore.java
I received an email from Daniel Yin for a bug in the MySQL store. This was a change that happened recently if you remember (not sure why the unit test didn't flag this then- maybe it wasn't run I guess).
The problem is to do with padding of the values that we really shouldn't need to worry about so hence this correction- it's now equivalent to the blob that was used previously. 
(I've also informed Daniel that he shouldn't email me directly. I only realised when I sent the reply. Create an issue or post on the forum for obvious reasons - the funniest being me and a big red bus :-)
=> MySQL data type fixed. Changed binary to varbinary.

.travis.yml, core/pom.xml
Travis builds have been failing excessively in the past weeks. The problem was enhanced by moving to the new Travis build infrastructure, but even before tests failed too often.
=> Make Travis not run any tests that involve accessing the network.

core/src/main/java/org/bitcoinj/core/AddressMessage.java, core/src/main/java/org/bitcoinj/core/Block.java, core/src/main/java/org/bitcoinj/core/ChildMessage.java, core/src/main/java/org/bitcoinj/core/ECKey.java, core/src/main/java/org/bitcoinj/core/EmptyMessage.java, core/src/main/java/org/bitcoinj/core/GetAddrMessage.java, core/src/main/java/org/bitcoinj/core/GetBlocksMessage.java, core/src/main/java/org/bitcoinj/core/GetDataMessage.java, core/src/main/java/org/bitcoinj/core/InventoryMessage.java, core/src/main/java/org/bitcoinj/core/ListMessage.java, core/src/main/java/org/bitcoinj/core/Message.java, core/src/main/java/org/bitcoinj/core/NetworkParameters.java, core/src/main/java/org/bitcoinj/core/PeerAddress.java, core/src/main/java/org/bitcoinj/core/RejectMessage.java, core/src/main/java/org/bitcoinj/core/StoredBlock.java, core/src/main/java/org/bitcoinj/core/StoredUndoableBlock.java, core/src/main/java/org/bitcoinj/core/Transaction.java, core/src/main/java/org/bitcoinj/core/TransactionConfidence.java, core/src/main/java/org/bitcoinj/core/TransactionInput.java, core/src/main/java/org/bitcoinj/core/TransactionOutPoint.java, core/src/main/java/org/bitcoinj/core/TransactionOutput.java, core/src/main/java/org/bitcoinj/core/UTXO.java, core/src/main/java/org/bitcoinj/core/UnknownMessage.java, core/src/main/java/org/bitcoinj/core/VersionMessage.java, core/src/main/java/org/bitcoinj/core/Wallet.java, core/src/main/java/org/bitcoinj/crypto/DeterministicHierarchy.java, core/src/main/java/org/bitcoinj/crypto/KeyCrypterScrypt.java, core/src/main/java/org/bitcoinj/store/MemoryFullPrunedBlockStore.java, core/src/test/java/org/bitcoinj/core/BlockTest.java
Remove Java serialization from
* NetworkParameters,
* the entire Message hierarchy,
* Block,
* StoredBlock,
* StoredUndoableBlock,
* TransactionConfidence,
* UTXO,
* DeterministicHierarchy,
* MemoryFullPrunedBlockStore and
* Wallet
It was largely untested, in many cases not working any more and we don't see a reason for supporting it.
=> Remove lots of Java serialization.

core/src/main/java/org/bitcoinj/core/Peer.java, core/src/main/java/org/bitcoinj/core/PeerSocketHandler.java, core/src/main/java/org/bitcoinj/net/BlockingClient.java, core/src/main/java/org/bitcoinj/net/BlockingClientManager.java, core/src/main/java/org/bitcoinj/net/ClientConnectionManager.java, core/src/main/java/org/bitcoinj/net/ConnectionHandler.java, core/src/main/java/org/bitcoinj/net/MessageWriteTarget.java, core/src/main/java/org/bitcoinj/net/NioClient.java, core/src/main/java/org/bitcoinj/net/NioClientManager.java, core/src/main/java/org/bitcoinj/net/NioServer.java, core/src/main/java/org/bitcoinj/net/ProtobufConnection.java, core/src/main/java/org/bitcoinj/net/StreamConnection.java, core/src/main/java/org/bitcoinj/net/StreamConnectionFactory.java, core/src/main/java/org/bitcoinj/protocols/channels/PaymentChannelClientConnection.java, core/src/main/java/org/bitcoinj/protocols/channels/PaymentChannelServerListener.java, core/src/main/java/org/bitcoinj/protocols/channels/ServerConnectionEventHandler.java, core/src/main/java/org/bitcoinj/testing/TestWithNetworkConnections.java, core/src/test/java/org/bitcoinj/net/NetworkAbstractionTests.java
After working with ProtobufParser for 1/2 a year (we use it in the Stroem implementation) I find the name misleading. A name change would be breaking, but I still request it.
The responsibility of PP is to read raw data and chunk it so that complete protobuf messages comes out. The name is probably a twist on its super class: StreamParser, but PP also has a "write()" method, which indicates that it also can send, not only parse. 
When working with payment channels I see PP as the main gateway to the network; when I call "write()" the message will be sent to the server, and I don't have to care much how it is done. The code I write would make more sense if the name is changed to ProtobufConnection.
=> Name change: ProtobufParser -> ProtobufConnection

pom.xml
It's pretty useless and it stands in the way of reproducible builds.
=> Don't add Maven descriptor to build artifacts.

core/src/main/java/org/bitcoinj/core/BitcoinSerializer.java, core/src/main/java/org/bitcoinj/core/Block.java, core/src/main/java/org/bitcoinj/core/DummySerializer.java, core/src/main/java/org/bitcoinj/core/HeadersMessage.java, core/src/main/java/org/bitcoinj/core/MessageSerializer.java
Add support for block headers of variable length, when parsing headers messages. Also removes a lot of double-handling of messages (i.e. copying subparts of the message out so they are parsed in isolation rather than within the context of the message)
=> Add support for block headers of variable length

core/src/main/java/org/bitcoinj/core/Block.java, core/src/main/java/org/bitcoinj/core/Transaction.java
They have been redundant since #1052 removed the respective maybeParse...() calls.
=> Remove redundant return statements

core/src/main/java/org/bitcoinj/core/Transaction.java
However, I'm not entirely convinced we need this. There will always be a certain percentage of nodes that use the old relay rules, e.g. Bitcoin XT. What do others think?
=> Set minimum fee to 5000 satoshis, matching Bitcoin Core 0.11.1.

core/src/main/java/org/bitcoinj/protocols/channels/PaymentChannelServerListener.java
This method was never actually called with any argument but `null` - this initialises it with the correct value.
=> Set connection channel in PaymentChannelServerListener

core/src/main/java/org/bitcoinj/protocols/channels/PaymentChannelServerState.java, core/src/main/java/org/bitcoinj/protocols/channels/StoredPaymentChannelClientStates.java, core/src/main/java/org/bitcoinj/protocols/channels/StoredPaymentChannelServerStates.java
* I added catch-all exception handlers to the `TimerTask` scheduled methods in the stored client and server channels - if something does fail during broadcast of transactions in either end of the payment channel then it won't take down the entire `TimerTask` with it now.
* I noticed that deserialised V2 servers weren't setting the expiry time correctly.
=> Fixed stored channel timers failing, fixed v2 server deserialisation

core/src/main/java/org/bitcoinj/core/Peer.java, core/src/main/java/org/bitcoinj/core/PeerGroup.java, core/src/main/java/org/bitcoinj/core/listeners/PeerConnectedEventListener.java, core/src/main/java/org/bitcoinj/core/listeners/PeerDisconnectedEventListener.java, core/src/main/java/org/bitcoinj/core/listeners/PeerDiscoveredEventListener.java, core/src/test/java/org/bitcoinj/core/BitcoindComparisonTool.java, core/src/test/java/org/bitcoinj/core/PeerGroupTest.java, core/src/test/java/org/bitcoinj/core/PeerTest.java, core/src/test/java/org/bitcoinj/testing/TestWithNetworkConnections.java, examples/src/main/java/org/bitcoinj/examples/PeerMonitor.java, examples/src/main/java/org/bitcoinj/examples/PrintPeers.java, tools/src/main/java/org/bitcoinj/tools/TestFeeLevel.java
Split PeerConnectionEventListener into individual connect, disconnect and discovery listeners.
Remove custom listener registration from Peer, as now it's possible to register a connect listener only, without a disconnect listener.
=> Split PeerConnectionEventListener

core/src/main/java/org/bitcoinj/core/Peer.java
This PR fixes two issues with the version handshake:
- Handshake is only complete when both halves (incoming and outgoing version+verack) are complete. Both of these halves run in parallel. Previously, in some cases we started sending messages even if the handshake wasn't complete.
- I the remote Peer sends main protocol messages while handshake is still in progress, that's a protocol violation. TODO investigate if we should pardon such violations and just log them.
=> Peer: Fix version handshake.

core/src/main/java/org/bitcoinj/core/Context.java, core/src/main/java/org/bitcoinj/core/Wallet.java, core/src/test/java/org/bitcoinj/core/AbstractFullPrunedBlockChainTest.java, core/src/test/java/org/bitcoinj/core/BlockChainTest.java, core/src/test/java/org/bitcoinj/core/ChainSplitTest.java, core/src/test/java/org/bitcoinj/core/TransactionBroadcastTest.java, core/src/test/java/org/bitcoinj/core/WalletTest.java, core/src/test/java/org/bitcoinj/protocols/channels/ChannelConnectionTest.java, core/src/test/java/org/bitcoinj/protocols/channels/PaymentChannelStateTest.java, core/src/test/java/org/bitcoinj/testing/TestWithNetworkConnections.java, core/src/test/java/org/bitcoinj/testing/TestWithWallet.java, examples/src/main/java/org/bitcoinj/examples/ExamplePaymentChannelClient.java
If you have been reading that field, you probably want to use Transaction.REFERENCE_DEFAULT_MIN_TX_FEE.
If you have been writing to that field to change the SendRequest.feePerKb default, use a Context.feePerKb
instead. There is also a new Context.ensureMinRequiredFee.
=> Get rid of SendRequest.DEFAULT_FEE_PER_KB "constant".

core/src/main/java/org/bitcoinj/core/BitcoinSerializer.java
Casting readUint32(...) to int could result in negative size. Causes crash at BitcoinSerializer.java:164
=> Fix Integer overflow in BitcoinSerializer.BitcoinPacketHeader

core/src/main/java/org/bitcoinj/core/Wallet.java, core/src/main/java/org/bitcoinj/protocols/channels/PaymentChannelClientState.java, core/src/main/java/org/bitcoinj/protocols/channels/PaymentChannelV1ClientState.java, core/src/main/java/org/bitcoinj/protocols/channels/PaymentChannelV2ClientState.java, core/src/test/java/org/bitcoinj/core/WalletTest.java, core/src/test/java/org/bitcoinj/protocols/channels/PaymentChannelStateTest.java
This commit sadly disables WalletTest.basicCategoryStepTest() because that test is not maintainable and
doesn't work any more. Hopefully we will rewrite fee solving together with a better set of unit tests.
=> Remove cent rule from fee solving in Wallet and payment channels.

core/src/main/java/org/bitcoinj/protocols/channels/IPaymentChannelClient.java, core/src/main/java/org/bitcoinj/protocols/channels/PaymentChannelClient.java, core/src/main/java/org/bitcoinj/protocols/channels/PaymentChannelClientConnection.java, core/src/main/java/org/bitcoinj/protocols/channels/PaymentChannelClientState.java, core/src/main/java/org/bitcoinj/protocols/channels/PaymentChannelServer.java, core/src/main/java/org/bitcoinj/protocols/channels/PaymentChannelV1ClientState.java, core/src/main/java/org/bitcoinj/protocols/channels/PaymentChannelV2ClientState.java, core/src/test/java/org/bitcoinj/protocols/channels/ChannelConnectionTest.java, core/src/test/java/org/bitcoinj/protocols/channels/PaymentChannelClientTest.java, core/src/test/java/org/bitcoinj/protocols/channels/PaymentChannelServerTest.java, core/src/test/java/org/bitcoinj/protocols/channels/PaymentChannelStateTest.java, examples/src/main/java/org/bitcoinj/examples/ExamplePaymentChannelClient.java
To allow for configurations of the payment channels without adding more parameters to the constructor, one can use the ClientChannelProperties and ServerChannelProperties. 
This change is breaking code using the non default constructors of the PaymentChannelClient, PaymentChannelClientConnection, PaymentChannelServer. 
To ensure that the interfaces can evolve without breaking future code, there are two default implementations DefaultClientChannelProperties, DefaultServerChanelProperties that uses the current default. See ExamplePaymentChannelClient for an example of how to use the DefaultClientChannelProperties.
=> Payment channels: ClientChannelProperties ServerChannelProperties

core/src/main/java/org/bitcoinj/core/Transaction.java
For me, by far the most common cause of `Content.get()`'s "Performing thread fixup" warnings is from when I call `Transaction.toString()` from a thread outside of BitcoinJ's control.
It doesn't seem like it's really necessary for the `toString()` to look something up in global state, so this change just avoids printing out the transaction confidence if it can't be looked up without a warning.
If you prefer, I'm happy to also do the simpler change of just removing confidence entirely from this `toString()`.
=> Remove Context requirement from Transaction.toString()

core/src/main/java/org/bitcoinj/core/Peer.java, core/src/main/java/org/bitcoinj/core/VersionMessage.java
They will fail the difficulty check anyway.
=> Peer: Drop Bitcoin Cash peers early, based on service bit 5.

core/src/main/java/org/bitcoinj/core/Transaction.java, core/src/main/java/org/bitcoinj/core/TransactionInput.java, core/src/main/java/org/bitcoinj/wallet/DefaultRiskAnalysis.java, core/src/test/java/org/bitcoinj/wallet/DefaultRiskAnalysisTest.java
Rather than considering all version 2 transactions risky, we now look more closely if any of its
inputs has a relative lock time. We can't check the relative locks though, because we usually
don't have the spent outputs (to know when they were creted).
=> Basic support for version 2 transactions.

core/src/main/java/org/bitcoinj/core/TransactionInput.java, core/src/main/java/org/bitcoinj/script/Script.java, core/src/test/java/org/bitcoinj/wallet/WalletTest.java
Segwit is another nail on the coffin, because for each pubkey there is now also a segwit address.
A number of wallets will not recognize returned payments if sent to the wrong address type.
=> Remove concept of 'from address'

core/src/main/java/org/bitcoinj/core/Address.java, core/src/main/java/org/bitcoinj/core/DumpedPrivateKey.java, core/src/main/java/org/bitcoinj/core/NetworkParameters.java, core/src/main/java/org/bitcoinj/core/WrongNetworkException.java, core/src/main/java/org/bitcoinj/params/MainNetParams.java, core/src/main/java/org/bitcoinj/params/TestNet2Params.java, core/src/main/java/org/bitcoinj/params/TestNet3Params.java, core/src/main/java/org/bitcoinj/params/UnitTestParams.java, core/src/test/java/org/bitcoinj/core/AddressTest.java
I just noticed I could extract this from my PR #1516 so it can be discussed and merged individually.
Description:
The concept was always weakly defined, as version headers have been used for different types of
data too (which wasn't included in the list). What's acceptable is always dependent on the
usecase, not only the network.
Also, with the coming Bech32 addresses there are no int version headers any more. Rather, it
uses an HRP (human readable part) which is a string.
This is an API breaking change, but I doubt many users have used this in the form of a list.
=> Remove the concept of "acceptable Base58 address headers" (version headers) for a given network.

core/src/main/java/org/bitcoinj/core/UTXOProvider.java, core/src/main/java/org/bitcoinj/store/DatabaseFullPrunedBlockStore.java, core/src/main/java/org/bitcoinj/store/LevelDBFullPrunedBlockStore.java, core/src/main/java/org/bitcoinj/store/MemoryFullPrunedBlockStore.java, core/src/main/java/org/bitcoinj/wallet/Wallet.java, core/src/test/java/org/bitcoinj/core/AbstractFullPrunedBlockChainTest.java, core/src/test/java/org/bitcoinj/core/TransactionInputTest.java
This is needed for supporting native segwit addresses throughout the entire API. Bitcoinj has actually always used UTXOProvider with ECKeys.
Unfortunately some implementations of UTXOProvider use legacy addresses as their database index, where they probably should be using the pubKeyHash: DatabaseFullPrunedBlockStore, MemoryFullPrunedBlockStore. I left the adaption of those stores to native segwit to later PRs. For now, they continue to work with legacy addresses. 
Pinging @kparmar1 because you've written the TODO comment that is resolved with this PR.
=> UTXOProvider: getOpenTransactionOutputs() to take a list of ECKeys rather than addresses.

core/src/main/java/org/bitcoinj/core/TransactionOutput.java, core/src/main/java/org/bitcoinj/script/Script.java, core/src/main/java/org/bitcoinj/script/ScriptPattern.java, core/src/main/java/org/bitcoinj/store/LevelDBFullPrunedBlockStore.java, core/src/main/java/org/bitcoinj/wallet/KeyChainGroup.java, core/src/main/java/org/bitcoinj/wallet/Wallet.java, core/src/test/java/org/bitcoinj/core/SegwitAddressTest.java, core/src/test/java/org/bitcoinj/script/ScriptPatternTest.java, core/src/test/java/org/bitcoinj/wallet/WalletTest.java
Teach SendRequest and Wallet to send to native segwit addresses.
Determine native segwit destination addresses of a transaction by parsing the segwit scriptPubKey.
=> Send to native segwit addresses

core/src/main/java/org/bitcoinj/wallet/DeterministicKeyChain.java, core/src/test/java/org/bitcoinj/wallet/WalletTest.java
This is related to https://github.com/bitcoinj/bitcoinj/commit/e0d9683bd54c4e60d71840ad1ab2409016a3e0f9, which was for allowing to encrypt a DeterminisiticKeyChain with an arbitrary path (besides m/0H).
When changing the `encryptWalletWithArbitraryPath` in `WalletTest` to include decryption (`encryptDecryptWalletWithArbitraryPath`), we find this failure:
```
[INFO] Running org.bitcoinj.wallet.WalletTest
[ERROR] Tests run: 123, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 15.943 s <<< FAILURE! - in org.bitcoinj.wallet.WalletTest
[ERROR] encryptDecryptWalletWithArbitraryPath(org.bitcoinj.wallet.WalletTest)  Time elapsed: 0.487 s  <<< ERROR!
org.bitcoinj.crypto.KeyCrypterException: Provided AES key is wrong
at org.bitcoinj.wallet.WalletTest.encryptWalletWithArbitraryPath(WalletTest.java: …
```
=> DeterministicKeyChain: Allow decrypting DeterministicKeyChain with arbitrary path

core/src/main/java/org/bitcoinj/crypto/DRMWorkaround.java
According to https://stackoverflow.com/questions/1179672/how-to-avoid-installing-unlimited-strength-jce-policy-files-when-deploying-an the workaround is not needed on OpenJDK.
@oscarguindzberg What do you think?
=> DRMWorkaround: Skip workaround on OpenJDK.

core/src/main/java/org/bitcoinj/core/AlertMessage.java, core/src/main/java/org/bitcoinj/core/ECKey.java, core/src/main/java/org/bitcoinj/core/SignatureDecodeException.java, core/src/main/java/org/bitcoinj/crypto/TransactionSignature.java, core/src/main/java/org/bitcoinj/net/discovery/HttpDiscovery.java, core/src/main/java/org/bitcoinj/protocols/channels/PaymentChannelClient.java, core/src/main/java/org/bitcoinj/protocols/channels/PaymentChannelServer.java, core/src/main/java/org/bitcoinj/protocols/channels/PaymentChannelServerState.java, core/src/main/java/org/bitcoinj/protocols/channels/PaymentChannelV1ClientState.java, core/src/main/java/org/bitcoinj/script/Script.java, core/src/main/java/org/bitcoinj/wallet/DefaultRiskAnalysis.java, core/src/test/java/org/bitcoinj/wallet/DefaultRiskAnalysisTest.java, examples/src/main/java/org/bitcoinj/examples/GenerateLowSTests.java
ECKey: If DER-encoded signatures cannot be parsed, throw SignatureDecodeException rather than RuntimeException.
=> Introduce SignatureDecodeException

core/src/main/java/org/bitcoinj/wallet/DefaultKeyChainFactory.java, core/src/main/java/org/bitcoinj/wallet/DeterministicKeyChain.java, core/src/main/java/org/bitcoinj/wallet/KeyChainGroup.java, core/src/main/java/org/bitcoinj/wallet/MarriedKeyChain.java, core/src/test/java/org/bitcoinj/store/WalletProtobufSerializerTest.java, core/src/test/java/org/bitcoinj/wallet/DeterministicKeyChainTest.java, core/src/test/java/org/bitcoinj/wallet/WalletTest.java
Migrate all use of constructors to use the builders instead.
While working on #1563 I noticed we will either break API or have an insane amount of constructors in DeterministicKeyChain and MarriedKeyChain. My proposal is to remove them all but the bare necessary and those that remain are considered unstable API in future. Consumers should use DeterministicKeyChain.builder() and MarriedKeyChain.builder().
Any comments on this?
@devrandom You added the builder pattern a good while ago.
=> DeterministicKeyChain, MarriedKeyChain: Remove most constructors and static constructors.

core/src/main/java/org/bitcoinj/kits/WalletAppKit.java, core/src/main/java/org/bitcoinj/wallet/KeyChainGroup.java, core/src/main/java/org/bitcoinj/wallet/Wallet.java, core/src/test/java/org/bitcoinj/core/BloomFilterTest.java, core/src/test/java/org/bitcoinj/core/FilteredBlockAndPartialMerkleTreeTests.java, core/src/test/java/org/bitcoinj/store/WalletProtobufSerializerTest.java, core/src/test/java/org/bitcoinj/testing/TestWithNetworkConnections.java, core/src/test/java/org/bitcoinj/wallet/DeterministicKeyChainTest.java, core/src/test/java/org/bitcoinj/wallet/KeyChainGroupTest.java, core/src/test/java/org/bitcoinj/wallet/WalletTest.java
KeyChainGroup: Remove most constructors. Those that remain are considered an unstable API.
Migrate all use of constructors to use a builder instead.
=> KeyChainGroup: Migrate constructors to builder pattern.

core/build.gradle
This should fix the 'address already in use' error.
=> build.gradle: Exclude the same set of integration tests as we did for Maven.

core/build.gradle, examples/build.gradle, settings.gradle, tools/build.gradle, wallettemplate/build.gradle
This lets us get rid of archivesBaseName and eclipse.project.name configurations.
=> settings.gradle: Prefix project names by 'bitcoinj-'.

core/src/main/java/org/bitcoinj/core/Utils.java, core/src/main/java/org/bitcoinj/wallet/Wallet.java, core/src/test/java/org/bitcoinj/protocols/channels/PaymentChannelStateTest.java
Completing ToDo, to replace remaining statements of `Utils.currentTimeMillis() / 1000` with `Utils. currentTimeSeconds()`.
=> Replace use of currentTimeMillis() with currentTimeSeconds() where appropriate.

README.md, settings.gradle
Debian Buster and Ubuntu Bionic, Cosmic and Disco now come with Gradle 4.4.1. Thus, I propose we raise the build requirement to Gradle 4.4.
This will allow us to use Gradle syntax and features that have become available between versions 3.4 and 4.4.
=> Require Gradle 4.4 (or above) for building.

.travis.yml
- Specify exact Gradle to use by running the Gradle wrapper in before_script.
- Pick several combinations of JDK version and Gradle version by building a matrix. See this example build: https://travis-ci.org/bitcoinj/bitcoinj/builds/521380652
@msgilligan What do you think of this? Would you pick other combinations?
=> .travis.yml: Specify exact Gradle version to use.

core/src/main/java/org/bitcoinj/core/Context.java, core/src/main/java/org/bitcoinj/core/Transaction.java, core/src/main/java/org/bitcoinj/wallet/SendRequest.java, core/src/main/java/org/bitcoinj/wallet/Wallet.java, core/src/test/java/org/bitcoinj/wallet/WalletTest.java, tools/src/main/java/org/bitcoinj/tools/WalletTool.java, tools/src/main/resources/org/bitcoinj/tools/wallet-tool-help.txt
Fee is now specified in virtual (kilo)bytes. For non-segwit transactions a virtual byte is the same as a byte so the change is backward compatible.
=> Wallet: Implement witness fee discount.

core/src/main/java/org/bitcoinj/core/LegacyAddress.java
As far as I can tell, they have all been deprecated in the 0.15 cycle. I propose to remove them to make further refactorings easier/smaller.
=> LegacyAddress: Remove deprecated methods.

core/src/main/java/org/bitcoinj/wallet/Wallet.java, core/src/test/java/org/bitcoinj/core/ChainSplitTest.java, core/src/test/java/org/bitcoinj/core/TransactionInputTest.java, core/src/test/java/org/bitcoinj/wallet/WalletTest.java, tools/src/main/java/org/bitcoinj/tools/WalletTool.java, wallettemplate/src/main/java/wallettemplate/Main.java, wallettemplate/src/main/java/wallettemplate/SendMoneyController.java
Coin selection is a per SendRequest, per createSend() or per getBalance() call affair.
Having it wallet-global can lead to race conditions, as sometimes experienced in the
WalletTest unit tests.
=> Wallet: Remove global coinSelector and allowSpendingUnconfirmedTransactions().

core/build.gradle, examples/build.gradle, tools/build.gradle, wallettemplate/build.gradle
Use the Gradle java-library plugin to make Guava an `api`
dependency since Guava types are used in the bitcoinj public API.
This is supported in Gradle 4.4.x: https://docs.gradle.org/4.4.1/userguide/java_library_plugin.html
=> Make Guava an `api` dependency using java-library

core/src/main/java/org/bitcoinj/core/Transaction.java, core/src/main/java/org/bitcoinj/signers/LocalTransactionSigner.java
In commit bc46e8518d677088b5b5a3a8dbdefa9958461c90, those two occurences of scriptCode building have been missed.
=> Transaction, LocalTransactionSigner: Fix P2WPKH signing.

wallettemplate/build.gradle
JavaFX 15 is released and is the now the latest supported version. It supports JDK 11 and later — same as the previous release.
Release notes are here:
https://github.com/openjdk/jfx/blob/jfx15/doc-files/release-notes-15.md#release-notes-for-javafx-15
=> wallettemplate: upgrade JavaFX to version 15

build.gradle
JCenter will stop accepting submission on February 28th and the repo will no longer be available on May 1st.
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/
=> build.gradle: Migrate repository from JCenter to Maven Central.

core/src/main/java/org/bitcoinj/core/AddressMessage.java, core/src/main/java/org/bitcoinj/core/ChildMessage.java, core/src/main/java/org/bitcoinj/core/Message.java, core/src/main/java/org/bitcoinj/core/PeerAddress.java, core/src/main/java/org/bitcoinj/core/VersionMessage.java, core/src/main/java/org/bitcoinj/wallet/WalletProtobufSerializer.java, core/src/test/java/org/bitcoinj/core/PeerAddressTest.java
It's contained in the MessageSerializer since a while.
=> Message hierarchy: Remove constructors that take a separate protocolVersion argument.

core/src/main/java/org/bitcoinj/core/VersionMessage.java, core/src/test/java/org/bitcoinj/core/VersionMessageTest.java
The minimum is 70000 anyway, and I'm pretty sure the code path wasn't properly tested.
=> VersionMessage: Remove support for protocol versions older than 106.

.github/workflows/gradle.yml
Use the `gradle/gradle-build-action` to build with a specified
version of Gradle. In our case, let’s use Gradle 6.9.
=> Github Actions: Build with Gradle 6.9

core/src/main/java/org/bitcoinj/params/MainNetParams.java, core/src/main/java/org/bitcoinj/params/RegTestParams.java, core/src/main/java/org/bitcoinj/params/TestNet3Params.java, core/src/main/java/org/bitcoinj/params/UnitTestParams.java
Reorganize the initialization of the constants in each NetworkParameters
subclasses so we can easily do diffs of `MainNetParms` vs `TestNet3Params`
and easily see how they are the same and how they are different.
I also reorganized the import statements so they “diff” better as well.
Other than those changes the only code I actually changed is
using the constant `PAYMENT_PROTOCOL_ID_UNIT_TESTS` instead of `“unittest”`
in `getPaymentProcolId()` in `UnitTestParams`.
This will help us with the next step which is to create symbolic constants
for some of the parameters for the genesis blocks.
=> Reorganize NetworkParameters subclasses for easy diffs

wallettemplate/src/main/java/wallettemplate/MainController.java, wallettemplate/src/main/resources/wallettemplate/main.fxml
I did this for two reasons:
1. So users will know why the buttons are there and that they work
2. A convenient way to test the informational alert function.
Draft PR: Waiting for PR #2196 to be merged, then I'll rebase, and submit.
=> walletfx: Hook up the unused “Primary” and “Secondary” buttons

wallettemplate/src/main/java/org/bitcoinj/walletfx/overlay/OverlayController.java, wallettemplate/src/main/java/org/bitcoinj/walletfx/overlay/OverlayableStackPaneController.java, wallettemplate/src/main/java/wallettemplate/MainController.java, wallettemplate/src/main/java/wallettemplate/SendMoneyController.java, wallettemplate/src/main/java/wallettemplate/WalletPasswordController.java, wallettemplate/src/main/java/wallettemplate/WalletSetPasswordController.java, wallettemplate/src/main/java/wallettemplate/WalletSettingsController.java, wallettemplate/src/main/java/wallettemplate/controls/ClickableBitcoinAddress.java
* Extract abstract class `OverlayableStackPaneController` from `MainController`
* Rename `OverlayWindowController` to `OverlayController` (`Window` was misleading)
Rationale:
1. Overlay functionality is independent of `MainContoller`’s wallet functions
2. Increases reusability of classes in this subproject
3. Prepares for further refactoring
=> walletfx: Extract OverlayableStackPaneController

wallettemplate/src/main/java/org/bitcoinj/walletfx/application/AppDelegate.java, wallettemplate/src/main/java/wallettemplate/Main.java, wallettemplate/src/main/java/wallettemplate/MainController.java, wallettemplate/src/main/java/wallettemplate/SendMoneyController.java, wallettemplate/src/main/java/wallettemplate/WalletPasswordController.java, wallettemplate/src/main/java/wallettemplate/WalletSetPasswordController.java, wallettemplate/src/main/java/wallettemplate/WalletSettingsController.java, wallettemplate/src/main/java/wallettemplate/WalletTemplate.java
* Introduce `AppDelegate` class for delegating JavaFX `Application`
* Move almost all of `Main` to `WalletTemplate`
Rationale:
* The “template” JavaFX Application main class (`Main`) is now about 30 lines of code
* `Main` class allows easy switching between TestNet and MainNet (in fact it could become a command-line argument) and other configuration changes (e.g. `preferredOutputScriptType`)
* Prepares the way for the next steps of refactoring
=> walletfx: Create WalletTemplate implementing AppDelegate

core/src/main/java/org/bitcoinj/wallet/BasicKeyChain.java, core/src/main/java/org/bitcoinj/wallet/DeterministicKeyChain.java, tools/src/main/java/org/bitcoinj/tools/WalletTool.java
This is meant to aid migration to protobuf-lite.
=> BasicKeyChain, DeterministicKeyChain, WalletTool: only use protobuf API that is available also on protobuf-lite.

README.md, core/build.gradle
It will still only use the Java 7 API.
=> build.gradle: produce Java 8 bytecode for the core module

tools/src/main/java/org/bitcoinj/tools/WalletTool.java
WalletTool: Implement two coin selection options for sending, `--select-addr=<address>` and `--select-output=<txid>:<index>`.
=> WalletTool: Implement two coin selection options for sending

core/src/main/java/org/bitcoinj/core/AddressFormatException.java, core/src/main/java/org/bitcoinj/core/Bech32.java, core/src/main/java/org/bitcoinj/core/SegwitAddress.java, core/src/test/java/org/bitcoinj/core/Bech32Test.java, core/src/test/java/org/bitcoinj/core/SegwitAddressTest.java
This implements the draft of BIP350. See https://github.com/bitcoin/bips/blob/master/bip-0350.mediawiki for details.
If there are no objections, I plan to merge this when it becomes clear that the spec won't change any more.
=> Implement Bech32m format for v1+ witness addresses

core/build.gradle
* update protobuf-javalite to 3.18.0 → probably a no-brainer
* update OkHttp to 3.14.9 → The 3.14 branch seems to be kind of long-term supported, although that is not officially announced. It's the last branch that doesn't come with the Kotlin deps. Note the the 3.12 branch is officially out of support at the end of 2021.
=> update protobuf-javalite to 3.18.0 and OkHttp to 3.14.9

core/src/main/java/org/bitcoinj/core/Transaction.java, core/src/main/java/org/bitcoinj/wallet/Wallet.java
The previous trick was confusing.
@alexandrupele This will not fix the fee issue, but it makes the division clearer, without casting to float and back.
=> Wallet, Transaction: use Guava IntMath.divide() for the round-up divisions

core/src/main/java/org/bitcoinj/script/Script.java, core/src/test/java/org/bitcoinj/wallet/WalletTest.java
This will (hopefully entirely) fix the slight fee underspending for spends from P2WPKH.
Fixes #2235.
=> Script: take into account the various witness length fields in getNumberOfBytesRequiredToSpend()

README.md
The Java runtime requirement is left unchanged at Java 8.
This would allow us to use more of the Java 8 API in core. Note we can always only use the subset of the two requirements, as we use one binary for both platforms.
=> README.md: update Android runtime requirement to Android 7.0

core/src/main/java/org/bitcoinj/core/ECKey.java
`FAKE_SIGNATURES` is a `public static boolean` that is `@VisibleForTesting` in `ECKey.java`. It is currently unused by any tests, so should be removed.
=> ECKey: Remove unused `public static boolean FAKE_SIGNATURES` 

README.md, settings.gradle, wallettool/build.gradle, wallettool/src/main/java/org/bitcoinj/wallettool/WalletTool.java
* Create a new module `bitcoinj-wallettool` in a new `wallettool` directory and move `WalletTool.java` into that submodule.
* Update the README build instructions for WalletTool to reflect the new directory.
* Remove the application plugin and it's configuration from `build.gradle` in the `tools` project.
=> WalletTool: Move to its own `wallettool` submodule

core/src/main/java/org/bitcoinj/core/MessageSerializer.java, core/src/main/java/org/bitcoinj/net/FilterMerger.java, core/src/main/java/org/bitcoinj/script/Script.java, core/src/test/java/org/bitcoinj/core/TransactionTest.java, wallettool/src/main/java/org/bitcoinj/wallettool/WalletTool.java
I propose to use consistent capitalization of the word segwit.
As noted in #2274, usage of "segwit" outnumbers "SegWit" by about 5-10x in the source code of Bitcoin Core, the BIPs and the bitcoin.org website.
=> global replace SegWit by segwit

core/src/main/java/org/bitcoinj/wallet/Wallet.java
* Make the three fields `final` and initialized in the constructor.
* Make the `List` `final`, too.
=> Wallet: Make BalanceFutureRequest less mutable

core/src/test/java/org/bitcoinj/wallet/BasicKeyChainTest.java
This should hopefully fix #1804, or at least make it very rare.
=> BasicKeyChainTest: fix spontaneous failure of bloom() because of false positive

core/src/main/java/org/bitcoinj/crypto/X509Utils.java
This fix should make the method compatible with JDK 18.
=> X509Utils: swallow CertificateParsingException in getDisplayNameFromCertificate() if certificate has no SubjectAltName extension

core/src/main/java/org/bitcoinj/wallet/WalletProtobufSerializer.java
I would actually locate those cases on our entire codebase, but there doesn't seem to be a refactoring for that in IntelliJ (though it seems to know about and verify the annotation).
=> WalletProtobufSerializer: declare WalletFactory a @FunctionalInterface

.github/workflows/graalvm.yml, wallettool/build.gradle, wallettool/src/main/graal/reflect-config.json, wallettool/src/main/graal/resource-config.json
At this checkpoint the tool builds and can run well enough to display help.
To build:
```
gradle clean bitcoinj-wallettool:nativeCompile
``` 
To run:
```
./wallettool/build/native/nativeCompile/wallet-tool --help
```
TODO:
=> wallet-tool: add graalvm `nativeCompile` support to `build.gradle`

core/src/main/java/org/bitcoinj/core/NetworkParameters.java, core/src/main/java/org/bitcoinj/params/AbstractBitcoinNetParams.java, core/src/main/java/org/bitcoinj/wallet/WalletProtobufSerializer.java
`fromID(String)` and `fromPmtProtocolID(String)` only know about Bitcoin networks so are deprecated and
moved to AbstractBitcoinNetParams.
When they are removed from `NetworkParameters` it will no longer be dependent on its subclasses.
=> NetworkParameters: deprecate/move fromID() to AbstractBitcoinNetParams

core/src/main/java/org/bitcoinj/core/Context.java, core/src/test/java/org/bitcoinj/core/TxConfidenceTableTest.java, integration-test/src/test/java/org/bitcoinj/core/FilteredBlockAndPartialMerkleTreeTest.java
We used to do this a long time ago, but switched the codebase to explicit propagation.
Generally, constructors should not have any side-effects.
=> Context: fix implicit context propagation by constructor

core/src/main/java/org/bitcoinj/base/BitcoinNetwork.java, core/src/test/java/org/bitcoinj/base/BitcoinNetworkTest.java
Also adds tests for of() and find().
=> BitcoinNetwork: allow a number of common alternate network names in find()

examples/src/main/java/org/bitcoinj/examples/ForwardingService.java
This means for mainnet and testnet, you don't have to provide the network name.
It will be inferred from the address. For signet and regtest however the network
name is still needed.
=> ForwardingService: infer network from address

core/src/main/java/org/bitcoinj/core/Transaction.java
Mobile devices have become very powerful over the years, so a specific optimization
like this should not be needed.
=> Transaction: remove the Android performance hack from getValue()

core/src/main/java/org/bitcoinj/core/ECKey.java, core/src/main/java/org/bitcoinj/crypto/HDKeyDerivation.java, core/src/main/java/org/bitcoinj/crypto/KeyCrypterScrypt.java, core/src/main/java/org/bitcoinj/wallet/KeyChainGroup.java
LinuxSecureRandom used to be initialized on Android because very old Android versions had a bug
in the random number generator. We don't support those old versions any more, so the workaround
has become unnecessary. It is still possible to initialize it manually if desired.
=> LinuxSecureRandom: don't automatically install RNG workaround any more

core/src/main/java/org/bitcoinj/kits/WalletAppKit.java
Remove the very long try/catch in startup that catches `BlockStoreException` and rethrows it wrapped in an `IOException`.
The Guava service base class (`AbstractIdleService`) that we are extending allows us to throw `Exception` so there is no reason to wrap the exception and it can just be thrown directly.
This is first step toward some further refactoring that will allow refactoring in `ForwardingService` to make it (and other apps that use `WalletAppKit`) more testable.
=> WalletAppKit: remove unnecessary try/catch in startUp()

core/src/main/java/org/bitcoinj/wallet/KeyChainGroup.java
It turns out the effect on unit-test runtime is negligible these days.
=> KeyChainGroup: remove the reduced lookahead for unit-tests

core/src/main/java/org/bitcoinj/wallet/Wallet.java, core/src/test/java/org/bitcoinj/wallet/WalletTest.java
Only one unit-test was dependent on it. That test has been changed to manually disable the shuffling.
=> Wallet: remove the output shuffling override for unit-tests

core/src/main/java/org/bitcoinj/core/PeerGroup.java
This fixes the missing context with PeerMonitor. See #2590.
=> PeerGroup: create a context as a convenience for apps that mainly operate on a PeerGroup

core/src/main/java/org/bitcoinj/core/Block.java, core/src/main/java/org/bitcoinj/core/Context.java, core/src/test/java/org/bitcoinj/core/AbstractFullPrunedBlockChainTest.java, core/src/test/java/org/bitcoinj/core/BlockChainTest.java, core/src/test/java/org/bitcoinj/core/ChainSplitTest.java, core/src/test/java/org/bitcoinj/testing/TestWithWallet.java, integration-test/src/test/java/org/bitcoinj/testing/TestWithNetworkConnections.java
This allows unit-tests to disable enforcement of proof of work, so that fake blocks
can be created and solved in short time.
This PR is working towards getting rid of `UnitTestParams`.
=> Context: introduce `relaxProofOfWork` property

core/src/main/java/org/bitcoinj/base/Base58.java, core/src/main/java/org/bitcoinj/base/exceptions/AddressFormatException.java, core/src/main/java/org/bitcoinj/core/DumpedPrivateKey.java, core/src/main/java/org/bitcoinj/core/EncodedPrivateKey.java, core/src/main/java/org/bitcoinj/crypto/BIP38PrivateKey.java, core/src/test/java/org/bitcoinj/core/EncodedPrivateKeyTest.java
After 1d5e752917db7b2a0ef6e8cc767876f267e7f044, the hierarchy only has private keys:
```
PrefixedChecksummedBytes (now EncodedPrivateKey)
- DumpedPrivateKey
- BIP38PrivateKey
```
=> PrefixedChecksummedBytes: rename to EncodedPrivateKey and update class-level JavaDoc

core/src/main/java/org/bitcoinj/core/Message.java
It had been used for Java Serialization.
=> Message: remove obsolete readObject() method

core/src/main/java/org/bitcoinj/core/Peer.java, core/src/main/java/org/bitcoinj/core/PeerGroup.java, core/src/main/java/org/bitcoinj/core/listeners/AddressEventListener.java
This has two commits:
74d54de1f6ec58c76e3a97df11df592be0a4f616 adds a new event and listener for receiving an `addr` or `addrv2` message by `Peer`.
3fffeee295f863dc1003e3ce37b72815558e52bf adds the actual discovery in `PeerGroup`.
=> Discover peers via P2P network

core/src/main/java/org/bitcoinj/core/SegwitAddress.java, core/src/test/java/org/bitcoinj/core/SegwitAddressTest.java
Hi @schildbach ! I have another PR, this time a very little change, but a little bit more reasoning behind it. So I'm very curious to hear your feedback. 🙂 
- This PR just adds a size check for Segwit v1 (Taproot) addresses to the `SegwitAddress` constructor so that it only accepts 32-byte long witness programs (the only valid length for Taproot as defined in [BIP 341](https://github.com/bitcoin/bips/blob/master/bip-0341.mediawiki#script-validation-rules)). 
- Adding this check means that `AddressParser.parseAddress(...)` will in future throw an exception for too short or too long Segwit v1 addresses (as it already does today for Segwit v0 addresses with invalid lengths). Currently too short/long Taproot addresses are accepted as valid by `AddressParser.parseAddress(...)`.
- Currently in …
=> SegwitAddress: include length check for Taproot witness programs

core/src/main/java/org/bitcoinj/core/Block.java, core/src/main/java/org/bitcoinj/core/FilteredBlock.java, core/src/main/java/org/bitcoinj/core/Message.java, core/src/main/java/org/bitcoinj/core/TransactionOutPoint.java
It's not implemented anyways and only used as a generalization of some subclass implementations.
=> Message: deprecate method getHash()

core/src/main/java/org/bitcoinj/base/internal/TimeUtils.java, core/src/main/java/org/bitcoinj/core/PeerGroup.java, core/src/main/java/org/bitcoinj/crypto/KeyCrypterScrypt.java, core/src/main/java/org/bitcoinj/crypto/MnemonicCode.java, core/src/main/java/org/bitcoinj/params/BitcoinNetworkParams.java, core/src/main/java/org/bitcoinj/wallet/DeterministicKeyChain.java, core/src/main/java/org/bitcoinj/wallet/WalletFiles.java, core/src/test/java/org/bitcoinj/store/SPVBlockStoreTest.java, integration-test/src/test/java/org/bitcoinj/core/PeerGroupTest.java
This replaces Guava Stopwatch usage by usage of `java.time.Instant` and `java.time.Duration`, aided by two new static helpers in `TimeUtils`.
Note: `java.time`requires Android API level 26, which I think we can safely require by now, either in this cycle (0.17) or next.
=> core, integration-test: migrate usage of Guava `Stopwatch` to `java.time` API

core/src/main/java/org/bitcoinj/core/listeners/DownloadProgressTracker.java, wallettemplate/src/main/java/org/bitcoinj/walletfx/utils/BitcoinUIModel.java
I'm aware the new method invokes the deprecated old method. I did not find an elegant way that works well for both unmigrated code and migrated code. It should go away with the removal of the deprecated method though.
=> DownloadProgressTracker: migrate `progress()` method to `java.time` API

core/src/test/java/org/bitcoinj/base/LegacyAddressTest.java, core/src/test/java/org/bitcoinj/script/ScriptPatternTest.java
This is an alternative proposal to #2769
The goal is to get rid of the `crypto` imports in LegacyAddressTest.
=> LegacyAddressTest: separate out and move part of p2shAddressCreationFromKeys

core/src/main/java/org/bitcoinj/crypto/MnemonicCode.java, core/src/main/java/org/bitcoinj/wallet/DeterministicSeed.java, core/src/test/java/org/bitcoinj/crypto/MnemonicCodeTest.java
When converting from entropy to mnemonic with `toMnemonic()`, a `MnemonicLengthException` was thrown for entropies with invalid length. This is bad for two reasons:
- it is a checked exception, and the method will not be called with user input
- misleading exception name, the error is about the entropy length not the mnemonic
We now throw a `RuntimeException` instead. The resulting simplification of calling code can be witnessed in `DeterministicSeed`.
=> MnemonicCode: in `toMnemonic()` throw unchecked rather than checked exception

core/src/main/java/org/bitcoinj/core/BitcoinSerializer.java, core/src/main/java/org/bitcoinj/core/Block.java, core/src/main/java/org/bitcoinj/core/DummySerializer.java, core/src/main/java/org/bitcoinj/core/HeadersMessage.java, core/src/main/java/org/bitcoinj/core/ListMessage.java, core/src/main/java/org/bitcoinj/core/Message.java, core/src/main/java/org/bitcoinj/core/MessageSerializer.java, core/src/main/java/org/bitcoinj/core/NetworkParameters.java, core/src/main/java/org/bitcoinj/params/BitcoinNetworkParams.java, core/src/main/java/org/bitcoinj/testing/MockAltNetworkParams.java, core/src/test/java/org/bitcoinj/core/BitcoinSerializerTest.java, core/src/test/java/org/bitcoinj/core/CheckpointManagerTest.java, core/src/test/java/org/bitcoinj/core/FullBlockTestGenerator.java, core/src/test/java/org/bitcoinj/core/ParseByteCacheTest.java, core/src/test/java/org/bitcoinj/core/PeerAddressTest.java, core/src/test/java/org/bitcoinj/core/SendHeadersMessageTest.java, integration-test/src/test/java/org/bitcoinj/core/FilteredBlockAndPartialMerkleTreeTest.java
This removes all caching of original message payload and "retain mode" in message serializers.
There is some effect on tests. Asserts on the cache status have been removed, rendering some tests almost pointless. Rather than removing them, comments have been added to explain the history of these tests. An assert on a large binary blob of a block was dependent on retain mode, likely due to non-optimal encoding. It had to be disabled.
Note: Some classes still cache individual values, like hashes.
=> Message: do away with retaining of original message payload

core/src/main/java/org/bitcoinj/base/internal/ByteUtils.java
This gets rid of a lot of manual bit shuffling.
Follow-up to #2846. Support for `ByteBuffer` will be needed if we use it for message (de)serialization.
=> ByteUtils: add reading from and writing to `ByteBuffer`

core/src/main/java/org/bitcoinj/core/AddressMessage.java, core/src/main/java/org/bitcoinj/core/AddressV1Message.java, core/src/main/java/org/bitcoinj/core/AddressV2Message.java, core/src/main/java/org/bitcoinj/core/Block.java, core/src/main/java/org/bitcoinj/core/BloomFilter.java, core/src/main/java/org/bitcoinj/core/ChildMessage.java, core/src/main/java/org/bitcoinj/core/EmptyMessage.java, core/src/main/java/org/bitcoinj/core/FilteredBlock.java, core/src/main/java/org/bitcoinj/core/GetBlocksMessage.java, core/src/main/java/org/bitcoinj/core/HeadersMessage.java, core/src/main/java/org/bitcoinj/core/ListMessage.java, core/src/main/java/org/bitcoinj/core/Message.java, core/src/main/java/org/bitcoinj/core/PartialMerkleTree.java, core/src/main/java/org/bitcoinj/core/PeerAddress.java, core/src/main/java/org/bitcoinj/core/Ping.java, core/src/main/java/org/bitcoinj/core/Pong.java, core/src/main/java/org/bitcoinj/core/RejectMessage.java, core/src/main/java/org/bitcoinj/core/Transaction.java, core/src/main/java/org/bitcoinj/core/TransactionInput.java, core/src/main/java/org/bitcoinj/core/TransactionOutPoint.java, core/src/main/java/org/bitcoinj/core/TransactionOutput.java, core/src/main/java/org/bitcoinj/core/TransactionWitness.java, core/src/main/java/org/bitcoinj/core/VersionMessage.java, core/src/test/java/org/bitcoinj/core/BlockTest.java, core/src/test/java/org/bitcoinj/core/FullBlockTestGenerator.java, core/src/test/java/org/bitcoinj/core/PeerAddressTest.java, core/src/test/java/org/bitcoinj/core/TransactionTest.java
This does away with a lot of updating the fields while parsing and mutating the data.
`getMessageSize()` now returns the length of the data as serialized by `bitcoinSerializeToStream()`, which can be different from the length of an original payload.
The default implementation of `getMessageSize()` is not performant enough for all usecases, to it is overridden in strategic subclasses to calculate the size in a much more efficient way.
=> Message: remove `length` and `optimalEncodingMessageSize` fields

core/src/main/java/org/bitcoinj/core/AddressMessage.java, core/src/main/java/org/bitcoinj/core/AddressV1Message.java, core/src/main/java/org/bitcoinj/core/AddressV2Message.java, core/src/main/java/org/bitcoinj/core/Block.java, core/src/main/java/org/bitcoinj/core/BloomFilter.java, core/src/main/java/org/bitcoinj/core/ChildMessage.java, core/src/main/java/org/bitcoinj/core/EmptyMessage.java, core/src/main/java/org/bitcoinj/core/FilteredBlock.java, core/src/main/java/org/bitcoinj/core/GetBlocksMessage.java, core/src/main/java/org/bitcoinj/core/HeadersMessage.java, core/src/main/java/org/bitcoinj/core/ListMessage.java, core/src/main/java/org/bitcoinj/core/Message.java, core/src/main/java/org/bitcoinj/core/PartialMerkleTree.java, core/src/main/java/org/bitcoinj/core/PeerAddress.java, core/src/main/java/org/bitcoinj/core/Ping.java, core/src/main/java/org/bitcoinj/core/Pong.java, core/src/main/java/org/bitcoinj/core/RejectMessage.java, core/src/main/java/org/bitcoinj/core/Transaction.java, core/src/main/java/org/bitcoinj/core/TransactionInput.java, core/src/main/java/org/bitcoinj/core/TransactionOutPoint.java, core/src/main/java/org/bitcoinj/core/TransactionOutput.java, core/src/main/java/org/bitcoinj/core/TransactionWitness.java, core/src/main/java/org/bitcoinj/core/UnknownMessage.java, core/src/main/java/org/bitcoinj/core/VersionMessage.java, core/src/test/java/org/bitcoinj/core/BlockTest.java, core/src/test/java/org/bitcoinj/core/FullBlockTestGenerator.java, core/src/test/java/org/bitcoinj/core/PeerAddressTest.java, core/src/test/java/org/bitcoinj/core/TransactionTest.java
This has the advantage of using the read position contained in `ByteBuffer`, so we remove our `offset` and `cursor` fields.
=> Message: parse the original `ByteBuffer`, rather than a copy of it

core/src/main/java/org/bitcoinj/core/ChildMessage.java, core/src/main/java/org/bitcoinj/core/Message.java, core/src/main/java/org/bitcoinj/core/PeerAddress.java
This requires two new pass-through constructors, but in return we get rid of the setter.
=> Message: make `serializer` field immutable

core/src/main/java/org/bitcoinj/core/Transaction.java, core/src/main/java/org/bitcoinj/wallet/Wallet.java, core/src/test/java/org/bitcoinj/core/BlockChainTest.java, core/src/test/java/org/bitcoinj/core/TransactionTest.java
That method is only needed in `Wallet`, so it's good to have it there. On top of that, Wallet will be able to provide `NetworkParameters` for a long time.
=> Transaction: move `isMature()` to `Wallet.isTransactionMature()`

core/src/main/java/org/bitcoinj/params/UnitTestParams.java
It won't really solve it anyway, because the difficulty check is disabled.
=> UnitTestParams: don't `solve()` the genesis block for unit tests

core/src/main/java/org/bitcoinj/core/TransactionOutput.java
This fix was applied on the 0.16 branch by a5fa4004047851180a4602914d7732bd33c10d35, but is not on `master` and is not in `bitcoinj-0.17-alpha1`.
=> TransactionOutput: fix regression with calculating getMinNonDustValue() for the multisig case

wallettool/src/main/java/org/bitcoinj/wallettool/WalletTool.java
Currently, only the transaction hash is printed.
Alternatively, we could add a switch to select txid, tx or nothing. Feels a bit like overkill though.
=> WalletTool: after `send` action, print the entire transaction

.gitignore, core/build.gradle
This is extracted from #3059, but also removes the old directory from `.gitignore`.
=> build.gradle: generate protobuf classes into the build directory

core/src/main/java/org/bitcoinj/base/internal/ByteUtils.java
I take it we agrred to not have unused read/write helpers. So this PR removes the currently unused.
=> ByteUtils: remove unused helpers

.github/workflows/gradle.yml
This is a backport of a similar change made on `master`.
=> gradle.yml: explicitly use ubuntu-22.04, macos-12, windows-2019

core/src/main/java/org/bitcoinj/core/StoredBlock.java
This is a fix for Issue #3410 that will allow main net blocks above 849,137 to be processed. As of block 849,138 we can no longer fit total chainwork in a 12-byte **signed** field. This fix "kicks the can down the road" by making the field 12-bytes **unsigned**.
We should open a new issue to address the long term need for bigger values. Note that converting the field to 12-byte unsigned precludes us from using the most-significant bit as a flag for a new format, but we should be able to pick some arbitrary value, say 0xA0 as a version flag and declare that values less than 0xA0 are "unversioned".
=> StoredBlock: use ByteUtils.bigIntegerToBytes to convert chainWork

core/src/main/java/org/bitcoinj/core/StoredBlock.java
This is a fix for Issue #3410 that will allow main net blocks above 849,137 to be processed. As of block 849,138 we can no longer fit total chainwork in a 12-byte *signed* field. This fix "kicks the can down the road" by making the field 12-bytes *unsigned*.
We should open a new issue to address the long term need for bigger values. Note that converting the field to 12-byte unsigned precludes us from using the most-significant bit as a flag for a new format, but we should be able to pick some arbitrary value, say 0xA0 as a version flag and declare that values less than 0xA0 are "unversioned".
This is a **BACKPORT** to the 0.16 branch. In the master/0.17 branch the bigIntegerToBytes method has been moved to base.internal.BytUtils, so this commit differs in that one respect.
=> StoredBlock: use Utils.bigIntegerToBytes to convert chainWork (Backport)

.gitlab-ci.yml
Trixie doesn't carry OpenJDK 21 any more, so our GitLab CI builds started failing. Because OpenJDK support under Debian is a moving target, it's better to remove it until Trixie is released. Otherwise, CI builds will start failing at any time.
=> .gitlab-ci.yml: remove build with OpenJDK 21 under Debian Trixie

core/src/main/java/org/bitcoinj/core/StoredBlock.java
We don't have unsafeBitcoinSerialize() any more.
=> StoredBlock: remove an outdated comment

core/src/main/java/org/bitcoinj/core/StoredBlock.java
The explicit list of usages was already stale. Rather, just mention it's being used internally.
=> StoredBlock: rework comment about usage of serializeCompact(), deserializeCompact()

core/src/main/java/org/bitcoinj/core/StoredBlock.java, core/src/test/java/org/bitcoinj/core/StoredBlockTest.java
The old format will soon run out of bytes for the chain work value.
Also deprecates the old methods and adds tests for the V2 format.
=> StoredBlock: add serializeCompactV2(), deserializeCompactV2()

core/src/main/java/org/bitcoinj/store/SPVBlockStore.java
It's an implementation detail. We should be switching this to private in future.
=> SPVBlockStore: deprecate constant `HEADER_MAGIC`

core/src/main/java/org/bitcoinj/store/SPVBlockStore.java
This is meant to make sure the buffer position is always right.
Followup to #3432
=> SPVBlockStore: rewind buffer directly before accesses to magic header

.gitlab-ci.yml, README.adoc, build.Containerfile, settings-debian.gradle
This is meant to prepare for improvements to the regular `settings.gradle` file.
GitLab pipeline, which is affected by these changes, succeeds: https://gitlab.com/bitcoinj/bitcoinj/-/pipelines/1427520217
=> settings-debian.gradle: separate out settings for builds on Debian Gradle 4.4

.github/workflows/gradle.yml, README.adoc, settings.gradle
Two reasons for picking that particular version:
* it enables us to replace all previous Gradle-related conditionals in this file
* it's required for official support of Java 17
Gitlab pipeline is fine: https://gitlab.com/bitcoinj/bitcoinj/-/pipelines/1428473105
=> settings.gradle: require Gradle 7.3 or later

.github/workflows/gradle.yml, .gitlab-ci.yml, README.adoc, settings-debian.gradle, settings.gradle
I didn't find a way to query for Java 17 compatibility on Gradle below 6.3, so I had to gate the overall check and our Gradle 4.4 build is unchecked.
=> settings.gradle: require JDK 17 for the build

.github/workflows/gradle.yml
This is the lowest version we support at the moment (apart from Debian Gradle). We should prevent it regressing without us noticing.
=> gradle.yml: add Gradle 7.3 to the build matrix

wallettool/build.gradle
I assume updating to most recent 0.10.2 would also bump our GraalVM requirement to 22 – seems excessive as our highest Java version is currently 21.
https://graalvm.github.io/native-build-tools/latest/index.html#changelog
=> build.gradle: update Gradle plugin for GraalVM to 0.10.2

examples-kotlin/build.gradle, integration-test/build.gradle, wallettemplate/build.gradle
For the remaining modules, we're still using Gradle 4.4 so we can't do the same.
Removing sourceCompatibility, targetCompatibility is for the next PR.
=> build.gradle: migrate `--release` compiler option to `compileJava.options.release` for wallettemplate, examples-kotlin

core/src/main/java/org/bitcoinj/base/Address.java, core/src/main/java/org/bitcoinj/base/LegacyAddress.java, core/src/main/java/org/bitcoinj/base/SegwitAddress.java, core/src/main/java/org/bitcoinj/base/package-info.java
Use `@code` rather than `@link` in these cases.
=> SegwitAddress, LegacyAddress, package-info.java: don't link to classes outside base in JavaDoc

core/src/main/java/org/bitcoinj/base/Address.java, core/src/main/java/org/bitcoinj/base/LegacyAddress.java, core/src/main/java/org/bitcoinj/base/SegwitAddress.java, core/src/main/java/org/bitcoinj/base/internal/ByteUtils.java, core/src/main/java/org/bitcoinj/base/package-info.java, core/src/main/java/org/bitcoinj/core/NetworkParameters.java
The idea of this patchset is to check if base has no unwanted dependencies to libraries or bitcoinj modules.
It was created this way:
- Remove all references of non-base packages (imports, fully qualified names)
- Try fix "cannot resolve symbol" compiler errors only by removing deprecated methods or variables
Optional: After the next release, we could merge this.
=> base: extinguish unwanted references from main classpath

core/src/main/java/org/bitcoinj/core/AbstractBlockChain.java, core/src/main/java/org/bitcoinj/core/Transaction.java, core/src/main/java/org/bitcoinj/wallet/DefaultRiskAnalysis.java, core/src/test/java/org/bitcoinj/core/FullBlockTestGenerator.java
Keep the old method as deprecated.
**This PR is against 0.17!**
If approved, I'll merge this to master as well, followed by a commit to remove the deprecated method.
=> Transaction: migrate isFinal() to Instant

core/src/main/java/org/bitcoinj/core/BaseMessage.java, core/src/main/java/org/bitcoinj/core/BloomFilter.java, core/src/main/java/org/bitcoinj/wallet/Wallet.java, core/src/test/java/org/bitcoinj/core/FullBlockTestGenerator.java
If this is approved, I'll merge it to 0.17 as well.
=> Message: remove references to deprecated bitcoinSerialize()

core/src/main/java/org/bitcoinj/core/AbstractBlockChain.java, core/src/main/java/org/bitcoinj/core/NetworkParameters.java, core/src/main/java/org/bitcoinj/params/BitcoinNetworkParams.java, core/src/main/java/org/bitcoinj/params/TestNet3Params.java, core/src/test/java/org/bitcoinj/core/BlockTest.java
If approved, I'll merge this to 0.17 as well.
=> Block: remove reference to deprecated getTimeSeconds()

core/src/main/java/org/bitcoinj/core/NetworkParameters.java
If possible, I'll backport this to 0.17 as well.
=> NetworkParameters: migrate constant `BIP16_ENFORCE_TIME` to Instant

core/src/main/java/org/bitcoinj/script/Script.java, core/src/main/java/org/bitcoinj/script/ScriptBuilder.java
This clarifies in the JavaDocs how `creationTime` is being used with `Script` and `ScriptBuilder`.
I extracted it from #3535 to perhaps be merged ahead/quicker.
=> Script, ScriptBuilder: clarify concept of creation time in the JavaDocs

core/build.gradle
Consider backporting this to 0.17.
=> build.gradle: update Bouncy Castle to 1.79

core/src/main/java/org/bitcoinj/script/ScriptPattern.java, core/src/test/java/org/bitcoinj/script/ScriptPatternTest.java
It now operates on bytes, rather than chunks. This also adds a bit of JavaDoc and a couple of tests.
This works towards #3545.
=> ScriptPattern: simplify `isWitnessCommitment()` and `extractWitnessCommitmentHash()`

core/src/main/java/org/bitcoinj/core/TransactionInput.java, core/src/main/java/org/bitcoinj/core/TransactionOutPoint.java
The reason is `write()` re-uses the `ByteBuffer`, whereas `serialize()` allocates an intermediate byte array.
If this is merged, I'll backport to 0.17.
=> TransactionInput, TransactionOutPoint: in write(), prefer calling write() over serialize()

core/src/main/java/org/bitcoinj/script/ScriptBuilder.java, core/src/test/java/org/bitcoinj/script/ScriptBuilderTest.java
Pushing an empty data is *not* a no-op: an item is added to the stack. So that empty array should be represented in the data part of the script chunk.
This makes behaviour consistent with script parsing, and input signing expects the empty array as a placeholder for a missing signature.
This reverts 07682145e3fbce4b278def8ab86003d2dc447442 from 2015!
Note: This kind-of bugfix is needed for some of my immutability work on TransactionInput.
Also adds a test.
=> ScriptBuilder: if pushing an empty data, use data() not smallNum()

core/src/main/java/org/bitcoinj/core/Transaction.java, core/src/main/java/org/bitcoinj/core/TransactionOutput.java, core/src/main/java/org/bitcoinj/wallet/Wallet.java, core/src/test/java/org/bitcoinj/core/TransactionTest.java
Because tweaking is necessary for fee calculation logic, these usages
have been changed to produce new TransactionOutputs instead and
replace them in transactions as needed.
This PR is a child of #3577, but could be changed to merge individually.
=> TransactionOutput: make field `value` immutable

core/src/main/java/org/bitcoinj/core/Transaction.java, core/src/main/java/org/bitcoinj/core/TransactionInput.java, core/src/main/java/org/bitcoinj/signers/LocalTransactionSigner.java, core/src/main/java/org/bitcoinj/signers/MissingSigResolutionSigner.java, core/src/main/java/org/bitcoinj/wallet/WalletProtobufSerializer.java, core/src/test/java/org/bitcoinj/core/TransactionTest.java, core/src/test/java/org/bitcoinj/wallet/WalletTest.java
Because tweaking is necessary for transaction signing, these usages
have been changed to produce new inputs instead and replace them in
transactions as needed.
This is a child of #3579, but could be made to merge independently.
=> TransactionInput: make field `witness` immutable

core/src/main/java/org/bitcoinj/core/Transaction.java, core/src/main/java/org/bitcoinj/core/TransactionInput.java, core/src/main/java/org/bitcoinj/signers/CustomTransactionSigner.java, core/src/main/java/org/bitcoinj/signers/LocalTransactionSigner.java, core/src/main/java/org/bitcoinj/signers/MissingSigResolutionSigner.java, core/src/main/java/org/bitcoinj/testing/FakeTxBuilder.java, core/src/main/java/org/bitcoinj/wallet/Wallet.java, core/src/test/java/org/bitcoinj/core/AbstractFullPrunedBlockChainTest.java, core/src/test/java/org/bitcoinj/core/FullBlockTestGenerator.java, core/src/test/java/org/bitcoinj/core/TransactionTest.java, core/src/test/java/org/bitcoinj/wallet/WalletTest.java, examples/src/main/java/org/bitcoinj/examples/GenerateLowSTests.java
Because tweaking is necessary for transaction signing, these usages
have been changed to produce new inputs instead and replace them in
transactions as needed.
This is a child of #3580, but could be made to merge individually.
=> TransactionInput: make field `scriptBytes` immutable

core/src/main/java/org/bitcoinj/core/TransactionWitness.java
If merged, I'll backport this to 0.17.
=> TransactionWitness: add missing class and method JavaDoc

core/src/main/java/org/bitcoinj/core/Transaction.java, core/src/main/java/org/bitcoinj/core/TransactionInput.java, core/src/main/java/org/bitcoinj/core/TransactionOutput.java, core/src/main/java/org/bitcoinj/core/TransactionWitness.java, core/src/main/java/org/bitcoinj/script/ScriptBuilder.java, core/src/main/java/org/bitcoinj/signers/CustomTransactionSigner.java, core/src/main/java/org/bitcoinj/signers/LocalTransactionSigner.java, core/src/main/java/org/bitcoinj/signers/MissingSigResolutionSigner.java, core/src/main/java/org/bitcoinj/testing/FakeTxBuilder.java, core/src/main/java/org/bitcoinj/wallet/Wallet.java, core/src/main/java/org/bitcoinj/wallet/WalletProtobufSerializer.java, core/src/test/java/org/bitcoinj/core/AbstractFullPrunedBlockChainTest.java, core/src/test/java/org/bitcoinj/core/BitcoinSerializerTest.java, core/src/test/java/org/bitcoinj/core/FullBlockTestGenerator.java, core/src/test/java/org/bitcoinj/core/TransactionTest.java, core/src/test/java/org/bitcoinj/script/ScriptBuilderTest.java, core/src/test/java/org/bitcoinj/script/ScriptTest.java, core/src/test/java/org/bitcoinj/store/WalletProtobufSerializerTest.java, core/src/test/java/org/bitcoinj/wallet/DefaultRiskAnalysisTest.java, core/src/test/java/org/bitcoinj/wallet/WalletTest.java, examples/src/main/java/org/bitcoinj/examples/GenerateLowSTests.java, integration-test/src/test/java/org/bitcoinj/core/PeerTest.java, wallettool/src/main/java/org/bitcoinj/wallettool/WalletTool.java
Without caching, transactions are serialized way too often.
This effectively reverts b8d3c4a641f1d6d7410f7152e5bd383b1f00c9ce, but invalidation is slightly different.
This PR has multiple commits, but **only the last commit is relevant for review**. All previous commits except the last are just backports of recent immutability work from master. We need that because it would be hard to detect mutations of dependant objects in order to properly invalidate caches.
If this is merged, I'll forward-port the relevant commit to master as well.
=> Transaction: cache transaction IDs

core/src/main/java/org/bitcoinj/params/MainNetParams.java, core/src/main/java/org/bitcoinj/params/SigNetParams.java, core/src/main/java/org/bitcoinj/params/TestNet3Params.java
This is a candicate for backport to 0.17, 0.16.
=> MainNetParams, TestNet3Params, SigNetParams: update DNS seeds from Bitcoin Core 28.1

designdocs/modular-architecture.md
According to https://www.slf4j.org/, this is the correct spelling.
=> modular-architecture.md: make SLF4J uppercase

base/src/main/java/org/bitcoinj/base/internal/ByteUtils.java
It's a maximum allowed size rather than a constant size. The `maxBytes` name makes this clearer.
=> ByteUtils: rename maxBytes parameter of bigIntegerToBytes()

core/src/main/java/org/bitcoinj/core/StoredBlock.java
Don't try to locate a previous block of the genesis block, using an arbitrary "previous block hash".
This could be backported to 0.17.
=> StoredBlock: if getPrev() called on a genesis block, cut short

core/src/main/java/org/bitcoinj/core/TransactionOutPoint.java, core/src/test/java/org/bitcoinj/core/FullBlockTestGenerator.java
- the output with given index has to exist in fromTx, and
- that output needs to match connectedOutput if given
This restriction causes a test to be unconstructable. It is replaced by the next best thing, but it's unclear if the test remains meaningful at all.
Child of #3636.
=> TransactionOutPoint: when constructing with known fromTx, do more integrity checks

core/src/main/java/org/bitcoinj/core/Transaction.java
This is a child of #3621 and #3622, but could be merged individually.
It used to be suppressed, presumably because coinbase scriptSigs may contain arbitrary bytes which could confuse our script parser.
=> Transaction: include coinbase input in toString()

core/src/main/java/org/bitcoinj/script/ScriptBuilder.java, core/src/test/java/org/bitcoinj/script/ScriptBuilderTest.java
Currently, there is no usecase for that.
=> ScriptBuilder: remove methods that add chunks at a specified index

core/src/main/java/org/bitcoinj/script/ScriptBuilder.java
This is a child of #3625, but it could be made to be merged independently if so desired.
We will need this to construct genesis block scriptSigs, which use a pushdata of a small value that would, optimally encoded, be pushed via OP_n.
=> ScriptBuilder: make bigNum() public

core/src/main/java/org/bitcoinj/params/BitcoinNetworkParams.java
In recent tests I've not seen a single value larger than 0 ms.
=> BitcoinNetworkParams: remove runtime measurement from checkDifficultyTransitions()

core/src/main/java/org/bitcoinj/core/Block.java
It requires the block to contain no transactions, so that a coinbase can be added. This is already true for all current usages.
This change allows us to get rid of another `unCacheTransactions()`.
=> Block: add precondition to test helper `addCoinbaseTransaction()`

base/src/main/java/org/bitcoinj/base/internal/Buffers.java, core/src/main/java/org/bitcoinj/core/PartialMerkleTree.java, core/src/main/java/org/bitcoinj/core/PeerAddress.java, core/src/main/java/org/bitcoinj/core/TransactionInput.java, core/src/main/java/org/bitcoinj/core/TransactionOutput.java, core/src/main/java/org/bitcoinj/core/TransactionWitness.java, core/src/test/java/org/bitcoinj/core/BuffersTest.java
Those determine the number of bytes that are written by `writeLengthPrefixedBytes()` and `writeLengthPrefixedString()`, respectively.
Also use the new helpers where appropriate.
=> Buffers: add helpers `lengthPrefixedBytesSize()` and `lengthPrefixedStringSize()`

core/src/main/java/org/bitcoinj/core/Block.java, core/src/main/java/org/bitcoinj/core/PartialMerkleTree.java, core/src/main/java/org/bitcoinj/core/Transaction.java, core/src/main/java/org/bitcoinj/core/TransactionInput.java, core/src/main/java/org/bitcoinj/core/TransactionOutput.java, core/src/main/java/org/bitcoinj/core/TransactionWitness.java
* replace variable re-assignments by concatenating additions
* use streams to walk and sum the various lists
Note: conditionals could be replaced with terniary expressions, but the resulting expression seems too difficult to understand as a whole.
This is another child of #3664.
=> Block, Transaction, TransactionInput, TransactionOutput, TransactionWitness: make `messageSize()` more functional

core/src/main/java/org/bitcoinj/core/AddressV1Message.java, core/src/main/java/org/bitcoinj/core/AddressV2Message.java, core/src/main/java/org/bitcoinj/core/BaseMessage.java, core/src/main/java/org/bitcoinj/core/BloomFilter.java, core/src/main/java/org/bitcoinj/core/FeeFilterMessage.java, core/src/main/java/org/bitcoinj/core/FilteredBlock.java, core/src/main/java/org/bitcoinj/core/GetBlocksMessage.java, core/src/main/java/org/bitcoinj/core/HeadersMessage.java, core/src/main/java/org/bitcoinj/core/ListMessage.java, core/src/main/java/org/bitcoinj/core/Ping.java, core/src/main/java/org/bitcoinj/core/Pong.java, core/src/main/java/org/bitcoinj/core/RejectMessage.java, core/src/main/java/org/bitcoinj/core/VersionMessage.java, core/src/test/java/org/bitcoinj/core/BitcoinSerializerTest.java
Implement it in the concrete implementations. This avoids needless serialization and instantiation of buffers.
=> BaseMessage: remove default implementation of `messageSize()`

core/src/main/java/org/bitcoinj/core/Transaction.java, core/src/test/java/org/bitcoinj/core/TransactionTest.java
It determines if segwit serialization should be used for this transaction, based on whether it has any witnesses and on protocol version.
Also renames variables/parameters to `useSegwitSerialization` to make clear it's about the serialization format.
=> Transaction: add helper `useSegwitSerialization()`

core/src/main/java/org/bitcoinj/core/Transaction.java
This also uses `Sha256Hash` for hashing.
=> Transaction: migrate `hashForWitnessSignature()` to ByteBuffer

core/src/main/java/org/bitcoinj/core/Transaction.java
This consists of 3 commits for easier reviewability.
=> Transaction: migrate hashForSignature() to ByteBuffer

core/src/main/java/org/bitcoinj/core/Block.java, core/src/main/java/org/bitcoinj/testing/FakeTxBuilder.java, core/src/test/java/org/bitcoinj/core/AbstractFullPrunedBlockChainTest.java, core/src/test/java/org/bitcoinj/core/ChainSplitTest.java, core/src/test/java/org/bitcoinj/core/FullBlockTestGenerator.java, core/src/test/java/org/bitcoinj/wallet/WalletTest.java, integration-test/src/test/java/org/bitcoinj/core/FilteredBlockAndPartialMerkleTreeTest.java, integration-test/src/test/java/org/bitcoinj/core/PeerGroupTest.java, integration-test/src/test/java/org/bitcoinj/core/PeerTest.java, integration-test/src/test/java/org/bitcoinj/core/TransactionBroadcastTest.java
Because `solve()` in almost all cases requires too much work, in future it should be called explicitly by the tests that depend on proper proof of work.
Most tests already use `Context.relaxProofOfWork` to skip the check. Only PeerTest depends on it, so it is changed to solve one block manually (on easiest difficulty).
Some method names were stripped of the adjective "solved" and the JavaDocs amended appropriately.
=> FakeTxBuilder: do not solve fake blocks

core/src/main/java/org/bitcoinj/core/Block.java, core/src/main/java/org/bitcoinj/core/Context.java
This removes both the boolean argument and the boolean return type. It always throws if difficulty target is not met. If it returns normally, the target is met.
The only consumer of the exception-safe usage mode is switched to using `Difficulty.isMetBy()` directly.
Also, this method is switched to private visibility.
This PR is a child of #3631.
=> Block: remove exception-safe usage mode from `checkProofOfWork()`

core/src/main/java/org/bitcoinj/core/Block.java, core/src/test/java/org/bitcoinj/core/BlockTest.java, core/src/test/java/org/bitcoinj/core/ChainSplitTest.java, core/src/test/java/org/bitcoinj/core/FullBlockTestGenerator.java
This is a more powerful replacement to the former helper `addTransaction(tx, runSanityChecks)`. Use it to get rid of direct mutations of the `transactions` field.
=> Block: add a test helper `replaceTransactions()`

core/src/main/java/org/bitcoinj/crypto/DeterministicKey.java, core/src/main/java/org/bitcoinj/wallet/DeterministicKeyChain.java
This breaks a test, so for now marked as draft.
org.bitcoinj.wallet.WalletTest#encryptDecryptWalletWithArbitraryPathAndScriptType
=> DeterministicKey: add `depth` to `equals()` and `hashCode()`

core/src/main/java/org/bitcoinj/crypto/DeterministicKey.java, core/src/main/java/org/bitcoinj/crypto/ECKey.java
Change two usages to construct the `LazyECPoint` themselves.
This is a child of #3700.
=> ECKey: make constructor based on `ECPoint` private

core/src/main/java/org/bitcoinj/crypto/HDPath.java
Make sure `list` can't be null.
=> HDPath: add a precondition to the canonical constructor

core/src/main/java/org/bitcoinj/crypto/DeterministicKey.java
Deterministic keys with depth greater than 255 cannot be serialized to Base58.
=> DeterministicKey: add note to JavaDoc of canonical constructor

core/src/main/java/org/bitcoinj/crypto/DeterministicKey.java, core/src/test/java/org/bitcoinj/crypto/ChildKeyDerivationTest.java
This method should not change anything but the parent. The canonical constructor is used to assure that.
Also adds asserts to `ChildKeyDerivationTest.pubOnlyDerivation()` to surface the issue.
=> DeterministicKey: fix depth issue with `dropParent()`

core/src/main/java/org/bitcoinj/crypto/DeterministicKey.java, core/src/main/java/org/bitcoinj/wallet/DeterministicKeyChain.java, core/src/test/java/org/bitcoinj/crypto/ChildKeyDerivationTest.java, core/src/test/java/org/bitcoinj/crypto/HDKeyDerivationTest.java, core/src/test/java/org/bitcoinj/testing/KeyChainTransactionSigner.java, core/src/test/java/org/bitcoinj/wallet/DeterministicKeyChainTest.java, core/src/test/java/org/bitcoinj/wallet/WalletTest.java
* use canonical constructor to clear both cleartext and encrypted private keys and the keyCrypter
* be more strict about returning same instance
* amend the JavaDoc
Also rename the method from `dropPrivateBytes()` and keep the old method around as deprecated.
~~This a child of #3715.~~
=> DeterministicKey: rewrite `withoutPrivateKey()`

core/src/main/java/org/bitcoinj/crypto/HDPath.java, core/src/test/java/org/bitcoinj/crypto/HDPathTest.java
Take the `hasPrivateKey` (prefix) into account.
Also add a test, and change some that don't work any more.
=> HDPath: implement `equals()` and `hashCode()`

core/src/main/java/org/bitcoinj/crypto/HDPath.java
~~This is a child of PR #3763~~
~~The first commit is a duplicate of PR #3770, so this should be rebased after that is merged.~~
There are two preparatory commits to remove the last usages of `List<ChildNumber>` and dependencies on `HDPath` implementing `List`. The third commit simply removes the `extend AbstractList<ChildNumber>` and removes `@Override` annotations on methods that exist in `AbstractList `.
=> HDPath: Do not inherit from List

core/src/main/java/org/bitcoinj/core/AbstractBlockChain.java, core/src/main/java/org/bitcoinj/core/Block.java, core/src/main/java/org/bitcoinj/core/BloomFilter.java, core/src/main/java/org/bitcoinj/core/CheckpointManager.java, core/src/main/java/org/bitcoinj/core/FilteredBlock.java, core/src/main/java/org/bitcoinj/core/HeadersMessage.java, core/src/main/java/org/bitcoinj/store/MemoryBlockStore.java, core/src/main/java/org/bitcoinj/store/MemoryFullPrunedBlockStore.java, core/src/main/java/org/bitcoinj/store/SPVBlockStore.java, core/src/test/java/org/bitcoinj/core/BlockChainTest.java, core/src/test/java/org/bitcoinj/core/BlockTest.java, core/src/test/java/org/bitcoinj/core/FullBlockTestGenerator.java, core/src/test/java/org/bitcoinj/store/SPVBlockStoreTest.java, integration-test/src/test/java/org/bitcoinj/core/PeerTest.java
Keep the old method around as deprecated.
Also make `writeHeader()` private. Any non-private usages are converted to `asHeader().write()`.
=> Block: rename to `asHeader()` from `cloneAsHeader()`

core/src/test/java/org/bitcoinj/core/FullBlockTestGenerator.java, core/src/test/java/org/bitcoinj/core/ParseByteCacheTest.java
This prevents accessing all transactions in these cases.
=> ParseByteCacheTest, FullBlockTestGenerator: make use of `Block.hasTransactions()`

core/src/main/java/org/bitcoinj/core/Block.java, core/src/main/java/org/bitcoinj/core/FullPrunedBlockChain.java, core/src/test/java/org/bitcoinj/core/BitcoindComparisonTool.java, core/src/test/java/org/bitcoinj/core/BlockTest.java, core/src/test/java/org/bitcoinj/core/FullBlockTestGenerator.java
Use it to prevent accessing `getTransactions()` when possible.
=> Block: add method `transactionCount()` to determine number of transactions

core/src/main/java/org/bitcoinj/core/Block.java, core/src/main/java/org/bitcoinj/core/Peer.java, core/src/test/java/org/bitcoinj/core/BlockTest.java, core/src/test/java/org/bitcoinj/core/FullBlockTestGenerator.java
Use it to prevent accessing `getTransactions()`
Child of #3687 and #3710.
=> Block: add iteration helper `forEachTransaction()`

core/src/main/java/org/bitcoinj/core/AbstractBlockChain.java, core/src/main/java/org/bitcoinj/core/Block.java, core/src/main/java/org/bitcoinj/core/BloomFilter.java, core/src/main/java/org/bitcoinj/core/FullPrunedBlockChain.java, core/src/main/java/org/bitcoinj/core/PeerGroup.java, core/src/test/java/org/bitcoinj/core/BlockTest.java, core/src/test/java/org/bitcoinj/core/FullBlockTestGenerator.java, core/src/test/java/org/bitcoinj/utils/BlockFileLoaderTest.java
The new method doesn't return null any more and throws instead.
The old method is kept around as deprecated.
=> Block: rename to `transactions()` from `getTransactions()`

core/src/main/java/org/bitcoinj/core/Block.java, core/src/main/java/org/bitcoinj/core/TestBlocks.java, core/src/main/java/org/bitcoinj/params/UnitTestParams.java, core/src/main/java/org/bitcoinj/testing/FakeTxBuilder.java, core/src/test/java/org/bitcoinj/core/AbstractFullPrunedBlockChainTest.java, core/src/test/java/org/bitcoinj/core/BlockChainTest.java, core/src/test/java/org/bitcoinj/core/BlockTest.java, core/src/test/java/org/bitcoinj/core/ChainSplitTest.java, core/src/test/java/org/bitcoinj/core/FullBlockTestGenerator.java, core/src/test/java/org/bitcoinj/core/TransactionTest.java, core/src/test/java/org/bitcoinj/store/SPVBlockStoreTest.java, core/src/test/java/org/bitcoinj/store/WalletProtobufSerializerTest.java, core/src/test/java/org/bitcoinj/wallet/WalletTest.java, integration-test/src/test/java/org/bitcoinj/core/PeerGroupTest.java
These helpers are moved to new helper `TestBlocks` as static methods:
- createNextBlock() and friends
- addCoinbaseTransaction()
- solve()
This is a child of #3650.
=> Block: separate out testing helpers

integration-test/src/test/java/org/bitcoinj/wallet/WalletAccountPathTest.java
@FieldSource is less verbose than @MethodSource
=> WalletAccountPathTest: Use @FieldSource for parameters

core/src/main/java/org/bitcoinj/core/FullPrunedBlockChain.java
A sequence of 9 commits to reduce usage of `NetworkParameters` by providing `Network`-based alternatives, reducing visibility, and using narrowed subtypes. They also remove a few uses of Guava's `@VisibleForTesting`.
=> Reduce usage of NetworkParameters in blockchain-related classes

core/src/main/java/org/bitcoinj/params/BitcoinNetworkParams.java
This is a child of PR #3732 and dependent upon PR #3731 to remove the last internal usage of the deprecated method.
=> BitcoinNetworkParams: deprecate fromId()

base/src/main/java/org/bitcoinj/base/BitcoinNetwork.java, base/src/main/java/org/bitcoinj/base/Network.java
Update the main JavaDoc for both classes to better explain when to use each type.
=> Network/BitcoinNetwork: Add usage guidelines to JavaDoc

core/src/main/java/org/bitcoinj/store/MemoryFullPrunedBlockStore.java
=> MemoryFullPrunedBlockStore: Network private member instead of NetworkParameters

core/src/main/java/org/bitcoinj/store/MemoryFullPrunedBlockStore.java
`TransactionalMultiKeyHashMap` is used a transaction `fullBlockMap` and has not been used for anything else for 13 years. Removing the type parameters and "de-genericizing" will make the code easier to read, enable further improvements, and hopefully performance optimizations that are specific to the "full block map" use case.
This is a sequence of 5 commits.
It is safe to consider this an internal class, so these changes are made without deprecation.
=> MemoryFullPrunedBlockStore: de-genericize TransactionalFullBlockMap from TransactionalMultiKeyHashMap

core/src/main/java/org/bitcoinj/core/FullPrunedBlockChain.java
Replace `FutureTask` with `CompletableFuture` and make further improvements using `CompletableFuture`.
4 commits.
Reviewer note: You may want to look at PR #3802 if you want to understand the 3rd commit (`FutureUtils.allAsList`) better.
=> FullPrunedBlockChain: Use CompletableFuture and FutureUtils in the 2 connectTransactions() methods

base/src/main/java/org/bitcoinj/base/internal/FutureUtils.java
FutureUtils remains useful even after we've removed all the deprecated Guava Future adapters. But the JavaDoc needed an update and the code needed to be more readable in order to update the JavaDoc.
6 commits.
=> FutureUtil: Improve JavaDoc and make more readable

core/src/main/java/org/bitcoinj/crypto/DeterministicHierarchy.java, core/src/main/java/org/bitcoinj/crypto/DeterministicKey.java, core/src/main/java/org/bitcoinj/crypto/HDKeyDerivation.java, core/src/test/java/org/bitcoinj/crypto/HDKeyDerivationTest.java, core/src/test/java/org/bitcoinj/wallet/DeterministicKeyChainTest.java
This is child of #3783 (but doesn't strictly need to be)
=> Remove incorrect usages of HDFullPath in deterministic key implementations

core/src/main/java/org/bitcoinj/core/TransactionOutPoint.java
To be disconnected the returned/modified TransactionOutPoint should have neither a `fromTx` or a `connectedOutput`.
=> TransactionOutPoint: have disconnectOutput() clear `fromTx`

core/src/test/java/org/bitcoinj/core/TransactionInputTest.java
This consists of two commits:
1. Improvements to tests and code comments to better test and document _current_ test behavior
2. The change to use `getConnectedOutput()` rather than `.connectedOutput` in `testStandardWalletDisconnect()`
Note that this is an improvement over changes in PR #3779 which simply removed the line:
```
assertNull(txInToDisconnect.getOutpoint().connectedOutput);
```
from `testStandardWalletDisconnect()`
Also for reference, see related PR #3816 which uses `getConnectedOutput()`  to simplify `TransactionInput.disconnect()`.
=> TransactionInputTest: use getConnectedOutput() in disconnect tests

core/src/main/java/org/bitcoinj/core/TransactionInput.java
`disconnect()` was duplicating the logic of `getConnectedOutput()` and can be simplified by using `getConnectedOutput()` directly.
=> TransactionInput: simplify disconnect() with outpoint.getConnectedOutput()

core/src/main/java/org/bitcoinj/core/TransactionOutPoint.java
This is a child of PR #3815 and includes a cherry-pick of PR #3816. Once those two PRs are merged this can rebased and will only contain a 1-line change to make `connectedOutput` `private`.
=> TransactionOutPoint: make connectedOutput private

core/src/main/java/org/bitcoinj/core/Utils.java
This contains commit to clean up Utils class since guava Joiner has been replaced by `InternalUtils.SPACE_JOINER`
=> Utils: Remove deprecated guava joiner and splitter

integration-test/build.gradle, wallettemplate/build.gradle, wallettool/build.gradle
By including the BOM, Gradle will automatically make sure all JUnit libraries use the same version. So we only need to specify the version on the BOM and the others will follow.
~~Using the BOM is required to get JUnit 5.12 to work with (at least certain versions of) Gradle.~~ I also had to add `org.junit.platform:junit-platform-launcher` so I'm not sure if both are required.
Gradle now requires explicit use of `junit-platform-launcher`, see: https://docs.gradle.org/8.12/userguide/upgrading_version_8.html#test_framework_implementation_dependencies
=> integration-test, wallettemplate, wallettool: Use JUnit BOM in build.gradle

integration-test/build.gradle, wallettemplate/build.gradle, wallettool/build.gradle
This is a child of PR #3773 -- it upgrades the version of the BOM and also adds  a runtime dependency on `junit-platform-launcher`
Gradle now requires explicit use of `junit-platform-launcher`, see: https://docs.gradle.org/8.12/userguide/upgrading_version_8.html#test_framework_implementation_dependencies
=> upgrade JUnit to 5.12.2 from 5.11.4

build.gradle, core/build.gradle
This is 2 commits: 1 for `protobuf-javalite` and 1 for the Gradle Protobuf Plugin. They are independent, but we might was well update both in the same PR.
Note the this update does not resolve Issue #3806 which is an upstream deprecation warning issue for Protobuf with Java 24.
=> Update protobuf-javalite to 4.30.2, Gradle Protobuf Plugin to 0.9.5

base/src/main/java/org/bitcoinj/base/internal/PlatformUtils.java, base/src/test/java/org/bitcoinj/base/internal/PlatformUtilsTest.java
Without this change the following message is displayed when running in a GraalVM native image:
```
Unknown java.runtime.name 'graalvm runtime environment'
```
We currently have no unit tests running in native images so I manually tested this by calling PlatformUtils.isGraalVMRuntime() from the wallet-tool both under both HotSpot and GraalVM and it worked correctly, returning `false` and `true`, respectively.
=> PlatformUtils: add Runtime.GRAALVM

core/src/main/java/org/bitcoinj/core/TransactionOutPoint.java
It is unused internally and is `disconnectOutput()` has more straightforward behavior (i.e. it completely disconnects the output)
=> TransactionOutPoint: deprecate disconnectTransaction()

core/src/main/java/org/bitcoinj/core/Transaction.java, core/src/main/java/org/bitcoinj/core/TransactionInput.java, core/src/main/java/org/bitcoinj/core/TransactionOutPoint.java, core/src/main/java/org/bitcoinj/core/TransactionOutput.java, core/src/main/java/org/bitcoinj/wallet/WalletProtobufSerializer.java, core/src/test/java/org/bitcoinj/core/AbstractFullPrunedBlockChainTest.java, core/src/test/java/org/bitcoinj/core/FullBlockTestGenerator.java, core/src/test/java/org/bitcoinj/core/TransactionOutPointTest.java, core/src/test/java/org/bitcoinj/core/TransactionTest.java, core/src/test/java/org/bitcoinj/script/ScriptTest.java, core/src/test/java/org/bitcoinj/wallet/WalletTest.java, integration-test/src/test/java/org/bitcoinj/core/PeerTest.java
`of()` constructor for a standalone outpoint, `from()` constructor that is connected to what it was constructed from.
Deprecate the two constructors that take a connected "fromTx" or a connected output and replace them with factory methods.
Deprecate (index, hash) constructor. Create private (hash, index) constructor. Replace with .of(hash, index) factory method.
This will allow us to factor out an interface or abstract base class in the future. It also completes our migration to hash parameter before index parameter.
=> TransactionOutPoint: static from() and of() constructors

core/src/main/java/org/bitcoinj/wallet/KeyChainGroup.java, wallettool/src/main/java/org/bitcoinj/wallettool/WalletTool.java
This ability was removed from `KeyChainGroup` with commit 4e8a19997d4c08d3e2633cf9368d0cef9b6f7ba7.
=> WalletTool: remove upgrade from basic to deterministic keychain

core/src/main/java/org/bitcoinj/store/MemoryFullPrunedBlockStore.java
In this way, replacing `.put` with `.putAll` will reduce and simplify the code
=> Replace put with putAll in MemoryFullPrunedBlockStore

core/src/main/java/org/bitcoinj/wallet/Wallet.java, core/src/test/java/org/bitcoinj/core/AbstractFullPrunedBlockChainTest.java, core/src/test/java/org/bitcoinj/core/TransactionInputTest.java
Deprecate getUTXOProvider/setUTXOProvider and protected methods that use the UTXOProvider methods.
We have plans to refactor and simplify the wallet interface and removing this mode of operation (which is rarely used outside of tests) will help us move in that direction.
Longer term, we hope to provide a more flexible wallet interface that will make it even easier to use other sources of UTXO information.
=> Wallet: deprecate UTXOProvider support

core/src/main/java/org/bitcoinj/core/PeerGroup.java
Improve the handling of the (positive or negative) excess connections in 3 commits
The variable `adjustment` was renamed to `excessConnections` and its sign was flipped. This makes the code more readable (no negation operator) and makes the variable name indicative of what positive and negative values mean.
=> PeerGroup: 3 minor improvements

core/src/main/java/org/bitcoinj/core/PeerGroup.java, core/src/main/java/org/bitcoinj/net/ClientConnectionManager.java
This contains a preliminary commit to simplify the JavaDoc of `ClientConnectionManager` before updating the comment as part of the main commit.
=> ClientConnectionManager: Deprecate inheritence of Guava `Service`

base/src/main/java/org/bitcoinj/base/Base58.java, core/src/main/java/org/bitcoinj/script/Script.java, core/src/main/java/org/bitcoinj/wallet/Wallet.java
Refactoring the use of `.length == 0` / `.size() == 0` to `.isEmpty()` will make the code more readable and correct
=> Refactor length and size checks to isEmpty

wallettemplate/src/main/java/module-info.java
Open o.b.walletfx.utils to javafx.fxml. This fixes clicking on the "primary" and "secondary" buttons.
=> wallettemplate module-info: open walletfx.utils

.github/workflows/gradle.yml, README.adoc, settings.gradle
The gradle.yml GHA workflow is updated to use 8.0 as the minimum Gradle in the matrix.
README.adoc is updated to specify 8.0 as the minimum for non-reference-builds.
This PR will allow us to upgrade to Kotlin 2.2.0. See PR #3857.
Note that Gradle 7 is unsupported now, even for critical bug and security fixes: https://endoflife.date/gradle
Having a minimum of 8.0 for non-reference builds could also make it easier us support Gradle 9 (see Issue #3859) since for non-reference-build modules, we won't have to support Gradle 7.
=> settings.gradle: set minGradleVersion to 8.0

wallettemplate/build.gradle, wallettemplate/src/main/java/module-info.java, wallettemplate/src/main/java/org/bitcoinj/walletfx/application/WalletApplication.java, wallettemplate/src/main/java/org/bitcoinj/walletfx/controls/NotificationBarPane.java, wallettemplate/src/main/java/org/bitcoinj/walletfx/overlay/OverlayableStackPaneController.java, wallettemplate/src/main/java/org/bitcoinj/walletfx/utils/KeyDerivationTasks.java, wallettemplate/src/main/java/org/bitcoinj/walletfx/utils/easing/package-info.java, wallettemplate/src/main/java/wallettemplate/WalletSettingsController.java
2 commits:
* use JSpecify instead of jakarta.annotation -- just update libraries and import statements)
* o.b.walletfx.utils.easing: add package-info.java with `@NullMarked` for the `easing` package.
=> wallettemplate: migrate to JSpecify

tools/build.gradle
`main` was deprecated in Gradle 8 and removed in Gradle 9.
`mainClass` was not added until Gradle 8, so we have to use a conditional to support Debian Gradle 4.4.
=> tools/build.gradle: use mainClass instead of main

core/build.gradle, integration-test/build.gradle
Instead of forcing usage of the Android version of Guava on the core `implementation` classpath, do it on the `testImplementation` classpath of both `core` and `integration-test`.
This makes sure our tests run against the Android version, which is what we really want. But with this change we can use the JRE version in other modules, such as the wallettemplate module.
=> core, integration-test: improve guava android constraint

integration-test/build.gradle, wallettemplate/build.gradle
This is needed for Gradle 9 compatibility.
=> integration-test, wallettemplate: add testRuntimeOnly junit-platform-launcher

wallettemplate/build.gradle, wallettemplate/src/main/java/module-info.java
Add a direct dependency on the latest, modular, JRE version of Guava: 33.4.8-jre.
* Add as an `implementation` dependency
* Use a resolution strategy to force the JRE version
* Add `com.google.common` to module-info.java
~~This is a child of PR #3877 and will need a rebase.~~ Rebased.
=> wallettemplate/build.gradle: direct dependency on Guava 33.4.8-jre

build.gradle
Gradle 9 removes the deprecated `dirMode` and `fileMode` settings, but dirPermissions/unix() was not added until Gradle 8.3.
This is an experiment and there might be another mechanism and/or something that was added earlier than 8.3.
We could also consider bumping the minimum supported (non-reference-build) Gradle to 8.3 or even Gradle 9.0+ (for Gradle 9+ we'd change the conditional to do nothing for the non Debian-4.4 build)
=> build.gradle: add hasConsistentArchives conditional for Gradle 9+

wallettool/build.gradle
We can't upgrade the asciidoctor Gradle plugin to 4.0.4 without breaking the Debian Gradle build.
Since the official builds are still on Debian Gradle and we aren't really "shipping" the generated man page, it is ok to disable this for now.
=> build.gradle: disable asciidoctor manpage generation on gradle 9+

.github/workflows/graalvm.yml
This prevents artifact uploading from breaking if we have two Gradle versions in the build matrix.
=> GHA graalvm.yml: Add -gradle-<version> to artifact name

.github/workflows/graalvm.yml, .github/workflows/gradle.yml
This has 3 cherry-picked commits, plus a 4th that adds `'9.1.0'` to the Gradle test matrix
In this draft PR we are testing in 8.14.3, 8.5, and 9.1.0. When we are ready to merge I propose we only use 8.5 and 9.1.0.
=> Gradle 9 (9.1.0) take 3

base/build.gradle, core/build.gradle, integration-test/build.gradle
EasyMock 5.6.0 is required for Java 25 compatibility.
=> build.gradle: Upgrade to EasyMock 5.6.0

integration-test/build.gradle
integration-tests require Gradle 8.5+ so this conditional is unneeded.
=> build.gradle: remove TargetJVM conditional in integration-tests module

.github/workflows/graalvm.yml
There's no reason not to replace EOL Java 23 with LTS Java 25 for our GraalVM-CE builds.
=> graalvm.yml: Use java 25 in the matrix (in place of 23)

settings-debian.gradle, settings.gradle
Minor changes to comments and ordering to make `settings.gradle` and `settings-debian.gradle` easier to compare.
=> settings*.gradle: normalize differences between the two files

integration-test/src/test/java/org/bitcoinj/testing/TestWithNetworkConnections.java, integration-test/src/test/java/org/bitcoinj/testing/TestWithPeerGroup.java
These two null checks prevent `DefaultMultiCauseException: Multiple Failures` during the intermittent `BindException: Address already in use: bind` we are seeing. They make the tearDown a little more orderly.
=> TestWithNetworkConnections, TestWithPeerGroup: handle nulls in tearDown()/stopPeerServer()
