bitcoinj/bitcoinj

- core/src/main/java/org/bitcoinj/wallet/DeterministicKeyChain.java
Add missing method to the builder
> DeterministicKeyChain Builder - add seedCreationTimeSecs()

- core/src/main/java/org/bitcoinj/core/PeerGroup.java
The previous 6 seconds caused otherwise quick peers to be disconnected too often.
> Adjust stall period to 15 seconds and min speed to 5 kB/s. And fix bugs.

- core/src/main/java/org/bitcoinj/core/AbstractBlockChain.java
- core/src/main/java/org/bitcoinj/core/NetworkParameters.java
- core/src/main/java/org/bitcoinj/core/PeerFilterProvider.java
- core/src/main/java/org/bitcoinj/core/Transaction.java
- core/src/main/java/org/bitcoinj/core/TxConfidenceTable.java
- core/src/main/java/org/bitcoinj/jni/NativeTransactionConfidenceListener.java
- core/src/main/java/org/bitcoinj/script/ScriptChunk.java
- core/src/main/java/org/bitcoinj/store/H2FullPrunedBlockStore.java
- core/src/main/java/org/bitcoinj/store/MySQLFullPrunedBlockStore.java
- core/src/main/java/org/bitcoinj/utils/BtcFixedFormat.java
- core/src/main/java/org/bitcoinj/wallet/DefaultKeyChainFactory.java
- core/src/main/java/org/bitcoinj/wallet/DeterministicSeed.java
- core/src/main/java/org/bitcoinj/wallet/KeyChainFactory.java
- core/src/main/java/org/bitcoinj/wallet/KeyChainGroup.java
- core/src/test/java/org/bitcoinj/core/VersionedChecksummedBytesTest.java
- core/src/test/java/org/bitcoinj/crypto/BIP32Test.java
- core/src/test/java/org/bitcoinj/wallet/KeyChainGroupTest.java
- examples/src/main/java/org/bitcoinj/examples/RefreshWallet.java
Hi
I removed some unused imports and unused local variables. (I did not modify the protos or variables used in tests.) I think it's important to get rid of unused code as it may shadow other problems.
> remove unused imports and unused local variables

- core/src/main/java/org/bitcoinj/core/Base58.java
- core/src/main/java/org/bitcoinj/core/BitcoinSerializer.java
- core/src/main/java/org/bitcoinj/core/Message.java
- core/src/main/java/org/bitcoinj/core/Utils.java
- core/src/main/java/org/bitcoinj/uri/BitcoinURI.java
- core/src/main/java/org/bitcoinj/wallet/DeterministicSeed.java
- core/src/test/java/org/bitcoinj/crypto/KeyCrypterScryptTest.java
- core/src/test/java/org/bitcoinj/uri/BitcoinURITest.java
> reduced unnecessary UnsupportedEncodingException handling

- core/src/test/java/org/bitcoinj/core/PeerGroupTest.java
The build fails occasionally with GitHub/Travis, or when I run 'mvn test -pl core -Dtest=PeerGroupTest' explicitly, although usually not when I do a full build. Can't be sure it fixes it (since failure is inconsistent), but I think it should help. Suggestions?
> Fix peerTimeoutTest intermittent failures.

- core/src/main/java/org/bitcoinj/core/Wallet.java
- core/src/test/java/org/bitcoinj/core/PeerTest.java
- core/src/test/java/org/bitcoinj/core/WalletTest.java
To match currentReceiveAddress()
> Rename getChangeAddress() to currentChangeAddress()

- core/src/main/java/org/bitcoinj/core/AbstractBlockChain.java
Ran into this unhelpful message while testing.
> Print block hash in debug log message for unconnectable orphan.

- core/src/main/java/org/bitcoinj/store/LevelDbFullPrunedBlockStore.java
- core/src/test/java/org/bitcoinj/core/LevelDbFullPrunedBlockChainTest.java
- examples/pom.xml
- examples/src/main/java/org/bitcoinj/examples/LevelDb.java
- examples/src/main/java/org/bitcoinj/examples/LevelDbSizes.java
and change to test logging to allow
unit tests to work on Travis. Without the log
change the unit tests fail due to hitting 4 Meg limit
> LevelDb fully pruned block store

- core/src/main/java/org/bitcoinj/core/TransactionOutput.java
- core/src/main/java/org/bitcoinj/protocols/channels/StoredPaymentChannelClientStates.java
- core/src/main/java/org/bitcoinj/protocols/channels/StoredPaymentChannelServerStates.java
This is largely esoteric, but was brought up by https://github.com/schildbach/bitcoin-wallet/issues/299.
> Fix a few max coins checks.

- core/src/main/java/org/bitcoinj/core/Transaction.java
- core/src/main/java/org/bitcoinj/core/TransactionOutput.java
- core/src/main/java/org/bitcoinj/protocols/channels/StoredPaymentChannelClientStates.java
- core/src/main/java/org/bitcoinj/protocols/channels/StoredPaymentChannelServerStates.java
- core/src/main/java/org/bitcoinj/protocols/payments/PaymentProtocol.java
- core/src/test/java/org/bitcoinj/core/TransactionTest.java
> Disable max money check on networks with no supply cap

- core/src/main/java/org/bitcoinj/core/listeners/PeerConnectionEventListener.java
- core/src/main/java/org/bitcoinj/core/listeners/PeerDataEventListener.java
Correct "procesesed" to "processed"
> Fix typo in PeerConnectionEventListener

- core/src/main/java/org/bitcoinj/core/PeerGroup.java
Something that becomes apparent in doing this, is that when we first register listeners they have an executor on the user thread, and if the peer dies they're then added with an executor on the same thread. Is that intentional?
> Refactor adding/removing block download listeners

- core/src/main/java/org/bitcoinj/store/DatabaseFullPrunedBlockStore.java
- core/src/main/java/org/bitcoinj/store/MySQLFullPrunedBlockStore.java
Minor spelling fixes.  trasaction -> transaction and databse -> database.
> DatabaseFullPrunedBlockStore, MySQLFullPrunedBlockStore: Fix spelling.

- core/src/main/java/org/bitcoin/Secp256k1Context.java
> Catch AccessControlException in Secp256k1Context initialization

- core/src/main/java/org/bitcoinj/store/SPVBlockStore.java
Most notably introduction of a custom capacity.
> A couple of changes to the SPVBlockstore

- core/src/main/java/org/bitcoinj/core/NetworkParameters.java
- core/src/main/java/org/bitcoinj/params/AbstractBitcoinNetParams.java
A couple of changes that work towards catching a rare problem with difficulty transitions.
> Difficulty transitions

- core/src/main/java/org/bitcoinj/params/MainNetParams.java
- core/src/main/java/org/bitcoinj/params/TestNet3Params.java
Seeds are copied from Bitcoin Core 0.13.1.
> Update seeds for mainnet and testnet.

- core/src/main/java/org/bitcoinj/core/Transaction.java
- core/src/main/java/org/bitcoinj/wallet/WalletProtobufSerializer.java
- core/src/test/java/org/bitcoinj/store/WalletProtobufSerializerTest.java
> Fix protobuf deserialization of transaction version.

- core/pom.xml
- core/src/main/java/org/bitcoinj/core/PeerGroup.java
- core/src/main/java/org/bitcoinj/net/discovery/HttpDiscovery.java
- core/src/main/java/org/bitcoinj/net/discovery/MultiplexingDiscovery.java
> Update to OkHttp 3.6.0.

- core/pom.xml
- core/src/main/java/org/bitcoinj/protocols/channels/PaymentChannelClient.java
- core/src/main/java/org/bitcoinj/protocols/channels/PaymentChannelServer.java
- examples/src/main/java/org/bitcoinj/examples/ForwardingService.java
This raises the Java API requirement to 1.7.
> Update to Guava 22.0-android.

- core/src/main/java/org/bitcoinj/core/GetDataMessage.java
- core/src/main/java/org/bitcoinj/core/Message.java
- core/src/main/java/org/bitcoinj/core/Peer.java
- core/src/main/java/org/bitcoinj/core/PeerGroup.java
- core/src/main/java/org/bitcoinj/core/VersionMessage.java
Testing this is a bit more challenging than it is for previous changes. The code though is obviously correct and does not make any existing tests fail. I will work on tests but decided to open this request earlier so it may be merged sooner at your discretion.
> Support P2P SegWit

- README.md
This is a possible solution to Issue #1712
> Add instructions for using Jitpack-powered SNAPSHOT builds

- core/build.gradle
- core/src/main/java/org/bitcoinj/crypto/BIP38PrivateKey.java
- core/src/main/java/org/bitcoinj/crypto/KeyCrypterScrypt.java
Amazingly, on a Pixel 2 this implementation is a bit quicker than Will Glozer/Colin Percival's native code.
> Use Bouncy Castle's Scrypt implementation rather than the standalone library.

- .travis.yml
The Bionic image is not yet official, so this is just WIP.
> .travis.yml: Use Ubuntu Bionic image for building.

- core/src/main/java/org/bitcoinj/core/AddressMessage.java
- core/src/main/java/org/bitcoinj/core/AddressV1Message.java
- core/src/main/java/org/bitcoinj/core/AddressV2Message.java
- core/src/main/java/org/bitcoinj/core/BitcoinSerializer.java
- core/src/main/java/org/bitcoinj/core/DummySerializer.java
- core/src/main/java/org/bitcoinj/core/MessageSerializer.java
- core/src/main/java/org/bitcoinj/core/Peer.java
- core/src/main/java/org/bitcoinj/core/PeerAddress.java
- core/src/main/java/org/bitcoinj/core/SendAddrV2Message.java
- core/src/main/java/org/bitcoinj/core/VersionMessage.java
- core/src/main/java/org/bitcoinj/wallet/WalletProtobufSerializer.java
- core/src/test/java/org/bitcoinj/core/AddressV1MessageTest.java
- core/src/test/java/org/bitcoinj/core/AddressV2MessageTest.java
- core/src/test/java/org/bitcoinj/core/BitcoinSerializerTest.java
- core/src/test/java/org/bitcoinj/core/PeerAddressTest.java
- core/src/test/java/org/bitcoinj/testing/TestWithPeerGroup.java
> BIP155: Address V2 messages

- wallettemplate/src/main/java/org/bitcoinj/walletfx/overlay/OverlayWindowController.java
- wallettemplate/src/main/java/wallettemplate/MainController.java
- wallettemplate/src/main/java/wallettemplate/SendMoneyController.java
- wallettemplate/src/main/java/wallettemplate/WalletPasswordController.java
- wallettemplate/src/main/java/wallettemplate/WalletSetPasswordController.java
- wallettemplate/src/main/java/wallettemplate/WalletSettingsController.java
- wallettemplate/src/main/java/wallettemplate/controls/ClickableBitcoinAddress.java
Rationale:
1. Stronger typing makes code more readable and refactorable
2. Eliminates “automatic” reflection in MainController
3. Makes overlayUI field in implementing classes private
4. Is a step towards further refactoring and reusability
> walletfx: Introduce OverlayWindowController interface

- wallettemplate/src/main/java/org/bitcoinj/walletfx/application/WalletApplication.java
- wallettemplate/src/main/java/wallettemplate/MainController.java
- wallettemplate/src/main/java/wallettemplate/SendMoneyController.java
- wallettemplate/src/main/java/wallettemplate/WalletPasswordController.java
- wallettemplate/src/main/java/wallettemplate/WalletSetPasswordController.java
- wallettemplate/src/main/java/wallettemplate/WalletSettingsController.java
- wallettemplate/src/main/java/wallettemplate/WalletTemplate.java
* Extract abstract class `WalletApplication` from `WalletTemplate`
* `WalletTemplate` implements `loadController()` with resource names
* `MainController`: Add `scene` member and `scene()` method
> walletfx: Extract `WalletApplication` from `WalletTemplate`

- wallettemplate/src/main/java/org/bitcoinj/walletfx/application/MainWindowController.java
- wallettemplate/src/main/java/org/bitcoinj/walletfx/application/WalletApplication.java
- wallettemplate/src/main/java/wallettemplate/MainController.java
- wallettemplate/src/main/java/wallettemplate/SendMoneyController.java
- wallettemplate/src/main/java/wallettemplate/WalletPasswordController.java
- wallettemplate/src/main/java/wallettemplate/WalletSetPasswordController.java
- wallettemplate/src/main/java/wallettemplate/WalletSettingsController.java
- wallettemplate/src/main/java/wallettemplate/WalletTemplate.java
* Extract `MainWindowController` from `wallettemplate.MainController`
* WalletApplication: `wallettemplate.MainController` with `MainWindowController`
> walletfx: Extract `MainWindowController` abstract base class

- wallettemplate/src/main/java/org/bitcoinj/walletfx/application/WalletApplication.java
- wallettemplate/src/main/java/wallettemplate/MainController.java
- wallettemplate/src/main/java/wallettemplate/WalletSettingsController.java
Dependent on PR #2210 (will need --potentially automatic -- rebase after that one is merged)
> walletfx: replace MainController.instance with `app.mainWindowController()`

- wallettemplate/src/main/java/org/bitcoinj/walletfx/application/WalletApplication.java
In WalletApplication:
* rename `realStart` to `startImpl`
* Factor out `WalletAppKit` initialization code to `startWalletAppKit` method
Rationale:
* Trying to separate `WalletAppKit` related startup from general JavaFX-related startupand more clearly identify what is depending upon having a `WalletAppKit` instance (this separation is still ongoing) 
* This helps identify items for further improvement like `WalletSetPasswordController.estimateKeyDerivationTimeMsec()` (see forthcoming PR)
> walletfx: factor out WalletApplication::startWalletAppKit

- core/src/main/java/org/bitcoinj/core/Base58.java
- core/src/main/java/org/bitcoinj/core/ECKey.java
- core/src/main/java/org/bitcoinj/core/Sha256Hash.java
- core/src/main/java/org/bitcoinj/core/StoredBlock.java
- core/src/main/java/org/bitcoinj/core/Utils.java
- core/src/main/java/org/bitcoinj/crypto/BIP38PrivateKey.java
- core/src/main/java/org/bitcoinj/crypto/DeterministicKey.java
- core/src/main/java/org/bitcoinj/crypto/HDKeyDerivation.java
- core/src/main/java/org/bitcoinj/wallet/DeterministicKeyChain.java
- core/src/test/java/org/bitcoinj/core/Base58DecodeToBigIntegerTest.java
- core/src/test/java/org/bitcoinj/core/ECKeyTest.java
- core/src/test/java/org/bitcoinj/core/UtilsTest.java
- wallettool/src/main/java/org/bitcoinj/wallettool/WalletTool.java
This is the antagonist to Utils.bigIntegerToBytes().
> Utils: add bytesToBigInteger() helper and use it

- core/src/test/java/org/bitcoinj/core/TransactionTest.java
This will actually fail the test if an assert in the worker threads fails.
Previously, it was just printing the exception to standard output.
> TransactionTest: rewrite testHashForSignatureThreadSafety() to use an executor

- core/src/main/java/org/bitcoinj/wallet/Wallet.java
Also simplify checkBalanceFuturesLocked()
> Wallet: Use CompletableFuture for BalanceFutureRequest

- core/src/main/java/org/bitcoinj/wallet/KeyChainGroup.java
- core/src/test/java/org/bitcoinj/wallet/KeyChainGroupTest.java
- core/src/test/java/org/bitcoinj/wallet/WalletTest.java
> KeyChainGroup: remove upgrade path from basic to deterministic

- core/src/main/java/org/bitcoinj/core/Coin.java
- core/src/main/java/org/bitcoinj/core/Monetary.java
- core/src/main/java/org/bitcoinj/core/PrefixedChecksummedBytes.java
- core/src/main/java/org/bitcoinj/core/Sha256Hash.java
- core/src/main/java/org/bitcoinj/crypto/KeyCrypter.java
- core/src/main/java/org/bitcoinj/protocols/payments/PaymentProtocol.java
- core/src/main/java/org/bitcoinj/utils/ExchangeRate.java
- core/src/main/java/org/bitcoinj/utils/Fiat.java
- core/src/test/java/org/bitcoinj/core/DumpedPrivateKeyTest.java
- core/src/test/java/org/bitcoinj/core/LegacyAddressTest.java
- core/src/test/java/org/bitcoinj/core/SegwitAddressTest.java
- core/src/test/java/org/bitcoinj/crypto/BIP38PrivateKeyTest.java
- core/src/test/java/org/bitcoinj/utils/ExchangeRateTest.java
* Remove all implementations of `Serializable`
* Remove unit tests of Java serialization
> Remove all usage of Java Serialization

- core/src/test/java/org/bitcoinj/core/BitcoindComparisonTool.java
- core/src/test/java/org/bitcoinj/core/BlockTest.java
- core/src/test/java/org/bitcoinj/core/TransactionTest.java
- core/src/test/java/org/bitcoinj/protocols/payments/PaymentSessionTest.java
- core/src/test/java/org/bitcoinj/script/ScriptTest.java
- core/src/test/java/org/bitcoinj/store/WalletProtobufSerializerTest.java
- core/src/test/java/org/bitcoinj/utils/VersionTallyTest.java
- tools/src/main/java/org/bitcoinj/tools/BlockImporter.java
This PR is dependent on #2488, so I'm opening this as draft.
> Context: remove useless Context instantiations from a few tests

- core/src/main/java/org/bitcoinj/core/AbstractBlockChain.java
- core/src/main/java/org/bitcoinj/core/BlockChain.java
- core/src/main/java/org/bitcoinj/core/CheckpointManager.java
- core/src/main/java/org/bitcoinj/core/Context.java
- core/src/main/java/org/bitcoinj/core/FullPrunedBlockChain.java
- core/src/main/java/org/bitcoinj/core/PeerGroup.java
- core/src/main/java/org/bitcoinj/kits/WalletAppKit.java
- core/src/main/java/org/bitcoinj/wallet/Wallet.java
- core/src/test/java/org/bitcoinj/core/AbstractFullPrunedBlockChainTest.java
- core/src/test/java/org/bitcoinj/core/BlockChainTest.java
- core/src/test/java/org/bitcoinj/core/BlockTest.java
- core/src/test/java/org/bitcoinj/core/BloomFilterTest.java
- core/src/test/java/org/bitcoinj/core/ChainSplitTest.java
- core/src/test/java/org/bitcoinj/core/ParseByteCacheTest.java
- core/src/test/java/org/bitcoinj/core/TransactionInputTest.java
- core/src/test/java/org/bitcoinj/core/TxConfidenceTableTest.java
- core/src/test/java/org/bitcoinj/store/WalletProtobufSerializerTest.java
- core/src/test/java/org/bitcoinj/testing/TestWithWallet.java
- core/src/test/java/org/bitcoinj/wallet/DefaultRiskAnalysisTest.java
- integration-test/src/test/java/org/bitcoinj/core/FilteredBlockAndPartialMerkleTreeTest.java
- integration-test/src/test/java/org/bitcoinj/testing/TestWithNetworkConnections.java
- integration-test/src/test/java/org/bitcoinj/wallet/WalletAccountPathTest.java
- integration-test/src/test/java/org/bitcoinj/wallet/WalletLoadTest.java
- tools/src/main/java/org/bitcoinj/tools/BuildCheckpoints.java
- wallettool/src/main/java/org/bitcoinj/wallettool/WalletTool.java
This is the first step in the goal of making Context optional again,
using it only for configuration of a test environment.
> Context: remove network parameters

- examples/src/main/java/org/bitcoinj/examples/ForwardingService.java
By using a CoinSelector that selects exactly the outputs that have been sent to us,
we make sure that
* we exactly send the value that has been sent to us, minus fee
* if the incoming transaction became invalid (e.g. due to a re-org),
our outgoing transaction would become invalid, too
Strictly speaking, after this PR we would not need to wait for confirmations any
more.
TODO maybe extract selector to wallet package, to be used by everyone?
> ForwardingService: make the forwarding a safe operation

- core/src/main/java/org/bitcoinj/core/TransactionBroadcast.java
* Add a private member called `sentFuture` that completes when the broadcast is "sent" (written to buffer) to the broadcast peers
* Update the `broadcast()` method to track success/failure of the individual broadcast messages and update `sentFuture` when the individual messages complete. (This is done by using `thenComposeAsync`/`whenComplete`)
* Add comments and TODOs
> TransactionBroadcast: internally create/complete `sentFuture`

- core/src/test/java/org/bitcoinj/base/Bech32Test.java
> Bech32Test: move to `base` package

- core/src/main/java/org/bitcoinj/net/discovery/SeedPeers.java
The old `int` format for peer addresses is now deprecated, as it doesn't support IPv6.
> SeedPeers: add a constructor for `InetSocketAddress`

- core/src/main/java/org/bitcoinj/base/Sha256Hash.java
- core/src/main/java/org/bitcoinj/core/Message.java
- core/src/test/java/org/bitcoinj/base/Sha256HashTest.java
> Sha256Hash: add reading from and writing to `ByteBuffer`

- core/src/main/java/org/bitcoinj/core/Peer.java
- core/src/main/java/org/bitcoinj/core/PeerAddress.java
- core/src/main/java/org/bitcoinj/core/PeerGroup.java
- core/src/main/java/org/bitcoinj/core/Services.java
- core/src/main/java/org/bitcoinj/core/VersionMessage.java
- core/src/main/java/org/bitcoinj/net/discovery/DnsDiscovery.java
- core/src/main/java/org/bitcoinj/net/discovery/MultiplexingDiscovery.java
- core/src/main/java/org/bitcoinj/net/discovery/PeerDiscovery.java
- core/src/main/java/org/bitcoinj/wallet/WalletProtobufSerializer.java
- core/src/test/java/org/bitcoinj/core/AddressV1MessageTest.java
- core/src/test/java/org/bitcoinj/core/AddressV2MessageTest.java
- core/src/test/java/org/bitcoinj/core/BitcoinSerializerTest.java
- core/src/test/java/org/bitcoinj/core/BitcoindComparisonTool.java
- core/src/test/java/org/bitcoinj/core/PeerAddressTest.java
- core/src/test/java/org/bitcoinj/core/ServicesTest.java
- core/src/test/java/org/bitcoinj/core/VersionMessageTest.java
- integration-test/src/test/java/org/bitcoinj/core/PeerGroupTest.java
- integration-test/src/test/java/org/bitcoinj/core/PeerTest.java
- integration-test/src/test/java/org/bitcoinj/core/TransactionBroadcastTest.java
- integration-test/src/test/java/org/bitcoinj/testing/TestWithPeerGroup.java
This was a holy mess of BigInteger, long, int and VarInt…
I'm mainly looking for concept ack. No JavaDoc has been written so far.
> Services: wrapper for node services bitfield

- core/src/main/java/org/bitcoinj/core/AddressV1Message.java
- core/src/main/java/org/bitcoinj/core/AddressV2Message.java
- core/src/main/java/org/bitcoinj/core/Block.java
- core/src/main/java/org/bitcoinj/core/BloomFilter.java
- core/src/main/java/org/bitcoinj/core/FeeFilterMessage.java
- core/src/main/java/org/bitcoinj/core/FilteredBlock.java
- core/src/main/java/org/bitcoinj/core/GetBlocksMessage.java
- core/src/main/java/org/bitcoinj/core/HeadersMessage.java
- core/src/main/java/org/bitcoinj/core/ListMessage.java
- core/src/main/java/org/bitcoinj/core/Message.java
- core/src/main/java/org/bitcoinj/core/PartialMerkleTree.java
- core/src/main/java/org/bitcoinj/core/PeerAddress.java
- core/src/main/java/org/bitcoinj/core/Ping.java
- core/src/main/java/org/bitcoinj/core/Pong.java
- core/src/main/java/org/bitcoinj/core/RejectMessage.java
- core/src/main/java/org/bitcoinj/core/Transaction.java
- core/src/main/java/org/bitcoinj/core/TransactionInput.java
- core/src/main/java/org/bitcoinj/core/TransactionOutPoint.java
- core/src/main/java/org/bitcoinj/core/TransactionOutput.java
- core/src/main/java/org/bitcoinj/core/VersionMessage.java
- core/src/test/java/org/bitcoinj/core/MessageTest.java
They were only calling through anyways.
> Message: inline all read helpers

- core/src/main/java/org/bitcoinj/core/PeerGroup.java
- core/src/main/java/org/bitcoinj/core/TransactionConfidence.java
- core/src/main/java/org/bitcoinj/crypto/DeterministicKey.java
- core/src/main/java/org/bitcoinj/crypto/ECKey.java
- core/src/main/java/org/bitcoinj/crypto/EncryptableItem.java
- core/src/main/java/org/bitcoinj/kits/WalletAppKit.java
- core/src/main/java/org/bitcoinj/wallet/BasicKeyChain.java
- core/src/main/java/org/bitcoinj/wallet/DeterministicKeyChain.java
- core/src/main/java/org/bitcoinj/wallet/DeterministicSeed.java
- core/src/main/java/org/bitcoinj/wallet/KeyTimeCoinSelector.java
- core/src/main/java/org/bitcoinj/wallet/Wallet.java
- core/src/main/java/org/bitcoinj/wallet/WalletProtobufSerializer.java
- core/src/test/java/org/bitcoinj/crypto/ECKeyTest.java
- core/src/test/java/org/bitcoinj/store/WalletProtobufSerializerTest.java
- core/src/test/java/org/bitcoinj/wallet/DeterministicKeyChainTest.java
- examples/src/main/java/org/bitcoinj/examples/BackupToMnemonicSeed.java
- integration-test/src/test/java/org/bitcoinj/core/PeerGroupTest.java
- integration-test/src/test/java/org/bitcoinj/wallet/WalletLoadTest.java
- wallettemplate/src/main/java/wallettemplate/WalletSettingsController.java
Works towards #2835, see details there.
> Revert some accessor renames

- .github/CONTRIBUTING.adoc
- core/src/main/java/org/bitcoinj/crypto/ECKey.java
Related: https://github.com/bitcoinj/bitcoinj.github.io/pull/59
> ECKey: remove mention of mailing list in documentation

- core/src/main/java/org/bitcoinj/store/SPVBlockStore.java
It's available as a field already.
> SPVBlockStore: don't pass buffer into setRingCursor(), getRingCursor()

- core/src/main/java/org/bitcoinj/store/SPVBlockStore.java
- core/src/test/java/org/bitcoinj/store/SPVBlockStoreTest.java
Existing V1 files are automatically converted to V2 format.
Followup of #3436.
> SPVBlockStore: support 32 byte chain work

- core/build.gradle
- examples-kotlin/build.gradle
- examples/build.gradle
- integration-test/build.gradle
- tools/build.gradle
- wallettemplate/build.gradle
- wallettool/build.gradle
We have defined `release` one way or another, and on JDK 17 that should suffice.
> build.gradle: remove `sourceCompatibility`, `targetCompatibility`

- core/src/main/java/org/bitcoinj/core/Block.java
- core/src/main/java/org/bitcoinj/core/CheckpointManager.java
- core/src/main/java/org/bitcoinj/core/Peer.java
- core/src/main/java/org/bitcoinj/core/PeerAddress.java
- core/src/main/java/org/bitcoinj/core/PeerFilterProvider.java
- core/src/main/java/org/bitcoinj/core/PeerGroup.java
- core/src/main/java/org/bitcoinj/crypto/EncryptableItem.java
- core/src/main/java/org/bitcoinj/kits/WalletAppKit.java
- core/src/main/java/org/bitcoinj/net/BlockingClientManager.java
- core/src/main/java/org/bitcoinj/net/discovery/PeerDiscovery.java
- core/src/main/java/org/bitcoinj/params/BitcoinNetworkParams.java
- core/src/main/java/org/bitcoinj/script/Script.java
- core/src/main/java/org/bitcoinj/testing/FakeTxBuilder.java
- core/src/main/java/org/bitcoinj/utils/ExponentialBackoff.java
- core/src/main/java/org/bitcoinj/wallet/BasicKeyChain.java
- core/src/main/java/org/bitcoinj/wallet/DeterministicKeyChain.java
- core/src/main/java/org/bitcoinj/wallet/DeterministicSeed.java
- core/src/main/java/org/bitcoinj/wallet/KeyTimeCoinSelector.java
- core/src/main/java/org/bitcoinj/wallet/Wallet.java
- core/src/main/java/org/bitcoinj/wallet/WalletFiles.java
- core/src/test/java/org/bitcoinj/net/discovery/DnsDiscoveryTest.java
I'll be extracting a bit of this PR to be merged ahead on master, and to be backported to 0.17.
> remove all usages of long as Instant or Duration

- core/src/main/java/org/bitcoinj/core/AbstractBlockChain.java
Child of #3502.
Will backport this to 0.17 if possible.
> AbstractBlockChain: migrate private getMedianTimestampOfRecentBlocks() to Instant

- .github/workflows/graalvm.yml
- .github/workflows/gradle.yml
> gradle.yml, graalvm.yml: update macOS to 13

- core/src/main/java/org/bitcoinj/core/Block.java
This is a child of #3626 and #3625.
In particular,
- the input script is constructed from the difficulty target and the genesis message
- the output script is constructed from the pubkey via ScriptBuilder.createP2PKOutputScript()
The added constants will be futher moved. This PR is preparing the stage for future refactorings.
> Block: construct genesis block coinbase from individual values

- core/src/main/java/org/bitcoinj/params/TestNet3Params.java
> TestNet3Params: fix difficulty transition check

- core/src/test/java/org/bitcoinj/core/BlockTest.java
- core/src/test/java/org/bitcoinj/core/TransactionTest.java
Three tests are changed to manually construct the out-of-spec serialized states designed to overwhelm `Transaction.read()`.
As a consequence, `HugeDeclaredSizeTransaction` is removed.
> TransactionTest: rewrite tests to do without `HugeDeclaredSizeTransaction`

- core/src/main/java/org/bitcoinj/core/StoredUndoableBlock.java
Also add `@Nullable` annotations, require non-null arguments to constructors, and make a field private.
> StoredUndoableBlock: make immutable

- core/src/main/java/org/bitcoinj/core/AbstractBlockChain.java
- core/src/main/java/org/bitcoinj/core/Block.java
- core/src/main/java/org/bitcoinj/core/NetworkParameters.java
- core/src/main/java/org/bitcoinj/core/StoredBlock.java
- core/src/main/java/org/bitcoinj/params/BitcoinNetworkParams.java
- core/src/main/java/org/bitcoinj/utils/VersionTally.java
- core/src/test/java/org/bitcoinj/core/BitcoindComparisonTool.java
- core/src/test/java/org/bitcoinj/core/BlockChainTest.java
- core/src/test/java/org/bitcoinj/core/FullBlockTestGenerator.java
- core/src/test/java/org/bitcoinj/utils/VersionTallyTest.java
- integration-test/src/test/java/org/bitcoinj/core/PeerGroupTest.java
Also rename accessor to `prevBlockHash()`. Keep the old as deprecated.
> Block: make field `prevBlockHash` immutable

- core/src/main/java/org/bitcoinj/crypto/DeterministicKey.java
Child of #3714.
On top of the canonical constructor commit, there are two fixes and then the corresponding tests that uncovered the bugs.
> DeterministicKey: add a canonical constructor and use it

- core/src/main/java/org/bitcoinj/crypto/LazyECPoint.java
> LazyECPoint: make immutable

- core/src/main/java/org/bitcoinj/wallet/DeterministicKeyChain.java
~~This is a child of PR #3762~~  
This is a child of:
* #3765
* #3766
It will need to be rebased when those are merged.
> DeterministicKeyChain: deprecate getAccountPath() 

- core/src/main/java/org/bitcoinj/wallet/Wallet.java
> Use HDPartialPath instead of List<ChildNumber> in a few classes

- core/src/main/java/org/bitcoinj/crypto/HDPath.java
~~This is a child of PR #3752~~ 
~~This should be rebased on PR #3764 once it is (hopefully) merged.~~
This consists of two commits: the first converts to `int[]` internally but with some intermediate usage of `List`. The second removes those intermediate `List` conversions to improve performance.
> HDPath: use int[] internally

- core/src/main/java/org/bitcoinj/core/AbstractBlockChain.java
- core/src/main/java/org/bitcoinj/core/DifficultyTransitions.java
- core/src/main/java/org/bitcoinj/core/NetworkParameters.java
- core/src/main/java/org/bitcoinj/core/StandardDifficultyTransitions.java
- core/src/main/java/org/bitcoinj/core/Testnet3DifficultyTransitions.java
- core/src/main/java/org/bitcoinj/params/BitcoinNetworkParams.java
- core/src/main/java/org/bitcoinj/params/TestNet3Params.java
- core/src/main/java/org/bitcoinj/testing/MockAltNetworkParams.java
- core/src/test/java/org/bitcoinj/core/StandardDifficultyTransitionsTest.java
- core/src/test/java/org/bitcoinj/params/BitcoinNetworkParamsTest.java
Extract logic from BitcoinNetworkParameters and TestNet3Params.
~~This is a child of #3631.~~
> DifficultyTransitions: interface and implementations for difficulty transitions

- core/src/test/java/org/bitcoinj/crypto/ChildKeyDerivationTest.java
> ChildKeyDerivationTest: amend testSerializationMainAndTestNetworks() to round-trip serialization

- core/src/main/java/org/bitcoinj/core/Block.java
- core/src/test/java/org/bitcoinj/core/FullBlockTestGenerator.java
> Block: add method `sigOpCount()` that sums up SigOps of transactions

- core/src/main/java/org/bitcoinj/core/AbstractBlockChain.java
- core/src/main/java/org/bitcoinj/core/Block.java
This is a possible follow-on to PR #3712
> Block: add findTransactions() and use in AbstractBlockChain

- core/src/main/java/org/bitcoinj/store/MemoryFullPrunedBlockStore.java
Replace custom `StoredTransactionOutPoint` with `TransactionOutPoint`.
> MemoryFullPrunedBlockStore: Use TransactionOutPoint

- wallettool/src/main/java/org/bitcoinj/wallettool/WalletTool.java
- Moved rawdump functionality into its own method. Made it rawdumpwallet static
- Moved send functionality into its own method.
> WalletTool: move actions to their own methods

- core/src/main/java/org/bitcoinj/crypto/HDPath.java
- core/src/main/java/org/bitcoinj/wallet/DeterministicKeyChain.java
12 commits of HDPath cleanup, simplification, optimization, and JavaDoc improvements.
> More HDPath simplification

- core/src/main/java/org/bitcoinj/core/TransactionInput.java
- core/src/main/java/org/bitcoinj/core/TransactionOutPoint.java
- core/src/test/java/org/bitcoinj/core/TransactionInputTest.java
> TransactionOutPoint: make fromTx field private

- designdocs/wallettool-subcommands.adoc
I have created a list of all subcommands and their options. The aim of doing this is to see what structure of the subcommands is most intuitive. Where should options be placed? what should be global and what should be local?
The structure in which we call the commands in CLI is identical to what we had before. The only change will be code changes each action/subcommand method will handle its own options as arguments passed to the method.
> WalletTool: Create design doc for WalletTool subcommands

- base/src/test/java/org/bitcoinj/base/internal/StopwatchTest.java
2 commits with minor improvements.
> StopwatchTest: add assert in toString_() test, fix typo in addSubtract() method name

- core/src/main/java/org/bitcoinj/core/Block.java
> Block: Simplify messageSize() with ternary

- core/build.gradle
~~This is a child of PR #3878 -- and will need a rebase.~~ rebased.
> core/build.gradle: update Guava to 33.4.8
